Feature/web scraping
mterada1228/keiba_expectation_app pull request #10
Opened 2020-11-26 01:28 UTC by mterada1228

- 修正内容
    - WebScrapingのために以下のGemを追加
      - `nokogiri`
      - `httparty`
    - Horseモデルをスクレイピングするスクリプトを作成
      - 取得サイト例: https://db.netkeiba.com/horse/2016105089

2020-11-26 05:51 UTC, ershn requested changes

2020-11-26 05:51 UTC, ershn commented on Gemfile.lock
>    puma (~> 4.1)
こちらのファイルは最新バージョンではないかと思います

2020-11-26 05:51 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +require 'HTTParty'
こちらは不要かと思います。

2020-11-26 05:51 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +    id: url.gsub(/\d+$/).first,
`gsub`は文字列内の一部を変えたい時に使うメソッドですが、データを抽出したい時は `/pattern/ =~ url` のようにした方が適切だと思います。

Ruby 2.2.7 のものですが、以下を一旦ご確認ください。
https://ruby-doc.org/core-2.2.7/Regexp.html

2020-11-26 05:51 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +    name: doc.css('div.horse_title > h1').children[0].text.gsub(/[[:space:]]/, '')
Chrome の Developer tools で css セレクターのコピー機能を活かせば、情報の抽出が楽になると思います。

2020-11-26 05:51 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +def create(data)
`data`という変数名は何を指すのかはわからないので、より具体的な名前にしたほうが保守性があがります。

2020-11-26 05:51 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +create(parse(html))
コマンドラインで呼ばれるのを想定するスクリプトだと思いますが、サービスクラスの形にしたほうがのちほど別の形での再利用が楽になります。

2020-12-02 02:14 UTC, mterada1228 commented on app/script/web_scraping/horse_scraper.rb
> +    name: doc.css('div.horse_title > h1').children[0].text.gsub(/[[:space:]]/, '')
ご連携ありがとうございます！活用いたします。

2020-12-02 03:00 UTC, mterada1228 commented on Gemfile.lock
>    puma (~> 4.1)
`bundle update`を実施し、こちらを最新化いたしました。

2020-12-02 03:02 UTC, mterada1228 commented on app/script/web_scraping/horse_scraper.rb
> +require 'HTTParty'
以下ファイルに移動しましたが、先頭行の `require 'HTTParty'`を削除致しました。

app/services/scraper/horse_scraper_service.rb

2020-12-02 03:03 UTC, mterada1228 commented on app/script/web_scraping/horse_scraper.rb
> +    id: url.gsub(/\d+$/).first,
app/services/scraper/horse_scraper_service.rbに移動しましたが、
以下のように修正いたしました。

```
id: /\d+$/.match(url)[0]
```

2020-12-02 03:03 UTC, mterada1228 commented on app/script/web_scraping/horse_scraper.rb
> +def create(data)
app/services/scraper/horse_scraper_service.rbに移動しましたが、
`data` => `attributes` に変更致しました。

2020-12-02 03:04 UTC, mterada1228 commented on app/script/web_scraping/horse_scraper.rb
> +create(parse(html))
app/services/scraper/horse_scraper_service.rbに移動しました。

2020-12-02 03:04 UTC, mterada1228 commented
先週はレビューありがとうございました。
修正致しましたのでご確認お願い致します。

2020-12-10 05:43 UTC, mterada1228 commented on app/services/scraper/horse_scraper_service.rb
> +      html = HTTParty.get(url)
`html`という名前というよりは`response` や `request` の方がふさわしい

2020-12-17 06:33 UTC, ershn commented on Gemfile.lock
>    puma (~> 4.1)
OK

2020-12-17 06:34 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +require 'HTTParty'
OK

2020-12-17 06:35 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +    id: url.gsub(/\d+$/).first,
OK

2020-12-17 06:35 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +    name: doc.css('div.horse_title > h1').children[0].text.gsub(/[[:space:]]/, '')
OK

2020-12-17 06:38 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +def create(data)
OK

2020-12-17 06:39 UTC, ershn commented on app/script/web_scraping/horse_scraper.rb
> +create(parse(html))
OK

2020-12-17 06:39 UTC, ershn commented on app/services/scraper/horse_scraper_service.rb
> +      html = HTTParty.get(url)
OK

2020-12-17 06:39 UTC, ershn approved these changes

2020-12-17 06:44 UTC, ershn reviewed
差分で不要なものが出ないように依存となってる PR をこちらの PR にマージし、diff 対象をその PR にしてもらえればと思います。

2020-12-17 06:44 UTC, ershn commented on app/services/scraper/horse_scraper_service.rb
> +    def create(attribute)
アトリビュートは複数含まれてるので、`attributes`の方が正しいです。

2020-12-17 06:44 UTC, ershn commented on app/services/scraper/race_result_scraper_service.rb
> +      @timeout = 4
こちらは動的に変わることがないので、定数にしておいたほうが適切です。

2020-12-17 06:47 UTC, ershn commented on app/services/scraper/horse_race_result_scraper_service.rb
> +            .match(race_result.children[9].children[0].attributes['href'].value)[1],
DOM にアクセスするための低レベルなインターフェイスを使うと、編集コストが上がって、可読性も下がるので、ここは css セレクターか xpath を使えれば楽になると思います。

2020-12-23 04:52 UTC, mterada1228 commented on db/schema.rb
> +  create_table "horse_race_results", id: :bigint, unsigned: true, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
修正前は `horse_id` と `race_result_id` の複合主キーとなっていました。  
このままだと `ActiveRecord` のメソッドが使用できないため、  
ナチュラルキーのIDを主キーとするように変更致しました。

2020-12-23 04:52 UTC, mterada1228 commented on app/services/scraper/horse_scraper_service.rb
> +    def create(attribute)
`app/services/scraper/*` で使用していた変数 `attribute` は `attributes` に変更しました。

2020-12-23 04:53 UTC, mterada1228 commented on app/services/scraper/race_result_scraper_service.rb
> +      @timeout = 4
`@wait_time`の使用箇所はなかったので削除しました。  
`@time_out` は `TIMEOUT` の定数に変更しました。

2020-12-23 04:54 UTC, mterada1228 commented on app/services/scraper/horse_race_result_scraper_service.rb
> +            .match(race_result.children[9].children[0].attributes['href'].value)[1],
css セレクターを使用して Element を取得するように変更しました。

2020-12-23 04:55 UTC, mterada1228 reviewed
@ershn レビューありがとうございました。
修正を行いましたので改めてレビューをお願い致します。

2020-12-24 05:52 UTC, mterada1228 reviewed
@ershn Race モデルのスクレイピングを追加しましたのでレビューをお願い致します。  
(取得元ページ例: https://race.netkeiba.com/race/shutuba.html?race_id=202006050711)

2020-12-24 05:52 UTC, mterada1228 commented on app/models/race.rb
> +  has_many :race_prizes
レコードを横持ちから縦持ちに変更するために以下のように変更しました。

(旧)  
`Race` に `regulation1, regulation2, regulation3...` と `prize1, prize2, prize3...` のカラムを持つ  
(新)
`RaceRegulation`, `RacePrize` モデルを追加して `race_id` で紐付ける

2020-12-24 05:52 UTC, mterada1228 commented on app/models/race.rb
> +  enum grade: { g1: 0, g2: 1, g3: 2, Listed: 3, op: 4, three_wins: 5, two_wins: 6, one_win: 7 }
入力値が限定されるカラムに `enum` を追加しました。

2020-12-24 05:52 UTC, mterada1228 commented on app/models/race.rb
> +  }.freeze
スクレイピングした値を、enum値に変換するためのハッシュです。

2020-12-24 05:52 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "course", null: false
`enum` に変換したので `string` => `integer` に変更しております。

2020-12-24 05:52 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "grade"
`enum` に変換したので `string` => `integer` に変更しております。

2021-01-07 05:41 UTC, ershn commented on app/services/scraper/horse_scraper_service.rb
> +    def create(attribute)
OK

2021-01-07 05:42 UTC, ershn commented on app/services/scraper/race_result_scraper_service.rb
> +      @timeout = 4
OK

2021-01-07 05:44 UTC, ershn commented on app/services/scraper/horse_race_result_scraper_service.rb
> +            .match(race_result.children[9].children[0].attributes['href'].value)[1],
OK

2021-01-07 06:06 UTC, ershn requested changes

2021-01-07 06:06 UTC, ershn commented on Gemfile.lock
>    webpacker (~> 4.0)
`bundle update`で色々更新されたという話かと思いますが、それで何が更新されるのかわからなくて、ものが意図せず壊れてしまうこともあるので、`bundle update`はやめて、必要な更新だけをした方が安全です。

2021-01-07 06:06 UTC, ershn commented on app/models/race.rb
>  end
レコードの間で重複するデータがあるように思いますので、重複がないように見直した方が簡単になると思います。

2021-01-07 06:06 UTC, ershn commented on app/models/race.rb
> +  enum grade: { g1: 0, g2: 1, g3: 2, Listed: 3, op: 4, three_wins: 5, two_wins: 6, one_win: 7 }
`Listed`だけに大文字が入ってます。

2021-01-12 01:29 UTC, mterada1228 commented on Gemfile.lock
>    webpacker (~> 4.0)
承知いたしました。
以降そのように対応致します。

2021-01-14 05:00 UTC, mterada1228 commented on app/models/race.rb
>  end
以下の方針で見直ししました。
1. `race_result`の重複するカラムを削除
     - `name`, `course_id`, `course_length`, `date`, `course_type`, `prize`
2. `race_result` に `race_id` を参照するようにカラムを追加
3.  `race_result`を参照していた`horse_race_result` の参照は`race`に変更

2021-01-14 05:01 UTC, mterada1228 commented on app/models/race.rb
> +  enum grade: { g1: 0, g2: 1, g3: 2, Listed: 3, op: 4, three_wins: 5, two_wins: 6, one_win: 7 }
`Listed` => `listed` に修正致しました。

2021-01-15 05:41 UTC, ershn commented on db/schema.rb
> +  create_table "horse_race_results", id: :bigint, unsigned: true, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
ActiveRecord はデフォルトで複合キーをサポートしてないので、composite_primary_keys の gem を入れて、主キーをモデルで指定すれば、エラーが解消されるかもしれません。

https://github.com/composite-primary-keys/composite_primary_keys

2021-01-15 05:45 UTC, ershn commented on app/models/race.rb
> +  has_many :race_prizes
了解です。いい修正だと思います。

2021-01-15 05:46 UTC, ershn commented on app/models/race.rb
> +  enum grade: { g1: 0, g2: 1, g3: 2, Listed: 3, op: 4, three_wins: 5, two_wins: 6, one_win: 7 }
OK

2021-01-15 05:46 UTC, ershn commented on app/models/race.rb
> +  }.freeze
OK

2021-01-15 05:46 UTC, ershn commented on db/schema.rb
> +    t.integer "course", null: false
OK

2021-01-15 05:47 UTC, ershn commented on db/schema.rb
> +    t.integer "grade"
OK

2021-01-15 05:47 UTC, ershn commented on Gemfile.lock
>    webpacker (~> 4.0)
OK

2021-01-15 05:50 UTC, ershn commented on app/models/race.rb
>  end
いいモデリングだと思います。

2021-01-15 05:50 UTC, ershn commented on app/models/race.rb
> +  enum grade: { g1: 0, g2: 1, g3: 2, Listed: 3, op: 4, three_wins: 5, two_wins: 6, one_win: 7 }
OK

2021-01-15 05:51 UTC, ershn commented on app/models/horse.rb
> +  has_one :race, through: :horse_race_results
has_many の方が正しいでは？

2021-01-15 05:56 UTC, ershn commented on app/services/scraper/horse_race_result_scraper_service.rb
> +        OPERATOR.each_key do |column_name|
`OPERATOR.each do |column, value|`でもいいかと思います。

2021-01-15 05:57 UTC, ershn commented on app/services/scraper/horse_race_result_scraper_service.rb
> +          attributes[column_name] = OPERATOR[column_name].call elements race_result
ここのメソッド呼び出しで括弧を使った方が読みやすいと思います。

2021-01-15 06:07 UTC, ershn requested changes
コメントを確認と対応してから、マージしていただいて問題ないです。ありがとうございます。

2021-01-21 04:46 UTC, mterada1228 commented on db/schema.rb
> +  create_table "horse_race_results", id: :bigint, unsigned: true, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
- Gemfileにconposite_primary_keysを追加しました。

- migationファイルを使用して、1. idカラムの削除、2. horse_id, primary_key を複合プライマリキーに変更しました。  

  - migration files:  
    - db/migrate/20210120013903_delete_id_and_add_composite_prymary_key_to_horse_id_and_race_id_to_horse_race_result.rb
    - db/migrate/20210121042512_add_foreign_key_horse_id_on_horse_race_result.rb

2021-01-21 04:47 UTC, mterada1228 commented on app/models/horse.rb
> +  has_one :race, through: :horse_race_results
`has_one` から `has_many` に relation を変更しました.

2021-01-21 04:47 UTC, mterada1228 commented on app/services/scraper/horse_race_result_scraper_service.rb
> +        OPERATOR.each_key do |column_name|
ご指摘の通りに修正を実施いたしました。

2021-01-21 04:50 UTC, mterada1228 commented on app/services/scraper/horse_race_result_scraper_service.rb
> +          attributes[column_name] = OPERATOR[column_name].call elements race_result
- `HorseRaceResultScraperService`
  - ループ外に`elements(rase_result)`呼び出しを記述しました
- それ以外の `** ScraperService`
  - |= 演算子を使用して、処理は一度しか呼ばれないように修正いたしました

2021-01-21 05:44 UTC, ershn commented on db/schema.rb
> +  create_table "horse_race_results", id: :bigint, unsigned: true, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
OK

2021-01-21 05:47 UTC, ershn commented on app/models/horse.rb
> +  has_one :race, through: :horse_race_results
OK

2021-01-21 05:48 UTC, ershn commented on app/services/scraper/horse_race_result_scraper_service.rb
> +        OPERATOR.each_key do |column_name|
OK

2021-01-21 05:55 UTC, ershn commented on app/services/scraper/race_scraper_service.rb
> +    end
`@var ||=`のキャッシュはできる場合は避けるべきで、クラスはできるだけステートレスな作りにする方が保守性が上がります。

ステートが増えれば増えるほど、バグが発生してしまう可能性があがるので。

---

`url`はコンストラクタ内に定義されて更新されないので、問題ないですが、`doc`は動的に変わるものなので、`elements`がその変数に依存することとして明示的に引数から受け取った方がわかりやすく保守しやすいです。

2021-01-21 05:56 UTC, ershn commented on app/services/scraper/horse_race_result_scraper_service.rb
> +          attributes[column_name] = OPERATOR[column_name].call elements race_result
OK

2021-01-21 05:57 UTC, ershn commented on app/services/scraper/race_result_scraper_service.rb
> +      @elements |= {
ここは`||=`ですね。

2021-01-22 03:01 UTC, mterada1228 commented on app/services/scraper/race_scraper_service.rb
> +    end
- `@elements ||=`呼び出しは削除しました。 
- `doc`はインスタンス変数ではなく、ローカル変数に変更しました。

2021-01-22 03:01 UTC, mterada1228 commented on app/services/scraper/race_result_scraper_service.rb
> +      @elements |= {
https://github.com/mterada1228/keiba_expectation_app/pull/10#discussion_r562357831 で '@elements ||=`呼び出しは削除しました。

2021-01-28 05:42 UTC, ershn commented on app/services/scraper/race_scraper_service.rb
> +    end
OK

2021-01-28 05:43 UTC, ershn commented on app/services/scraper/race_result_scraper_service.rb
> +      @elements |= {
OK

2021-01-29 01:54 UTC, merged