Feature/delete race result and change from horse race result to horse race
mterada1228/keiba_expectation_app pull request #11
Opened 2021-01-25 04:32 UTC by mterada1228

- エラーメッセージを日本語翻訳できるようにした
    - rails-i18nのgemをインストール
    - I18n.t は省略可能になったので t. に変更(spec/配下以外)
  - horse_race_result を horse_race に名称変更
    - ソース中のhorse_race_resultsをhorse_racesにrename
    - rails db:migrate を用いてテーブル名を rename
  - race_horse を削除
    - ソース中のrace_resultsを削除。代わりにhorse_racesを呼び出す形に修正
    - race_horse モデルの削除
    - race_horse に関する migration ファイルを削除
  - race_scraper_serviceのバグ修正

2021-01-28 05:55 UTC, ershn requested changes

2021-01-28 05:55 UTC, ershn commented on Gemfile
> +gem 'rails-i18n'
こちらはバージョン指定がかけてるようです。

2021-01-29 02:13 UTC, mterada1228 commented on Gemfile
> +gem 'rails-i18n'
`gem 'rails-i18n', '~> 6.0'` に修正しました

2021-02-18 04:32 UTC, ershn commented on Gemfile
> +gem 'rails-i18n'
OK

2021-02-18 04:33 UTC, ershn approved these changes

2021-02-18 05:04 UTC, merged