Feature/add job of web scraping
mterada1228/keiba_expectation_app pull request #12
Opened 2021-02-18 03:24 UTC by mterada1228

2021-02-25 04:55 UTC, ershn requested changes
レビューしましたので、ご確認ください。

2021-02-25 04:55 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +    def setup
こちらは`private`にできると思います。

2021-02-25 04:55 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        end
`each`でキーとバリューを一気に受け取れると思います。

2021-02-25 04:55 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        return nil if elements[:horse_weight].text == '計不' || elements[:horse_weight].text.blank?
`return`に`nil`をパラメーターとして渡さなくても、`nil`が返されます。

2021-02-25 04:55 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        elements[:gate_number].text.present? ? elements[:gate_number].text : nil
ここは`presence`を使えると思います。

2021-02-25 04:55 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +    attr_reader :url, :driver
これは不要だと思います。

2021-02-25 04:55 UTC, ershn commented on app/services/scraper/race_result_from_race_tab_scraper_service.rb
> +        rap_time_info: doc.css('#tab_ResultSelect_1_con > div.Result_Pay_Back.mb5 > div.ResultPayback.Block_Inline > div.Table_Scroll > table > tbody > tr:nth-child(3) > td'),
文字列は分割できます。

```ruby
'testestest' \
'testtesttest'
```

2021-02-25 04:55 UTC, ershn commented on app/services/scraper/top_page_scraper_service.rb
> +      ActiveRecord::Base.logger = Logger.new($stdout)
ロガーはところどころ作るのを避けて、使いまわしたほうが保守性がいいです。

後はできるなら、Rails のロガーを使ったほうがいいです。

2021-02-25 04:55 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +end
スクレイピングクラスでやってるのは以下の３つだと思います。

- データをスクレープして、ハッシュとして情報をまとめる
- そのデータを使って、レコードを作成する
- 必要に応じて他のクラスを呼び出す

ただし、それだと、単一責任の原則が守られず、保守性が下がるので、用途別でクラスを分けたほうがいいと思います。そうすれば、テストもしやすくなります。

2021-03-04 03:10 UTC, mterada1228 commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +    def setup
`setup` メソッドは全て `private` に変更いたしました。

2021-03-04 03:11 UTC, mterada1228 commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        end
`each_key` は `each` に変更し、`key` と `value` を受け取るように変更いたしました。

2021-03-04 03:11 UTC, mterada1228 commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        return nil if elements[:horse_weight].text == '計不' || elements[:horse_weight].text.blank?
`return nil` は `return` のみに変更いたしました。

2021-03-04 03:12 UTC, mterada1228 commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        elements[:gate_number].text.present? ? elements[:gate_number].text : nil
`present? == true` の場合、レシーバを返す場合、`precence` を使用するよう変更しました。

2021-03-04 03:12 UTC, mterada1228 commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +    attr_reader :url, :driver
`attr_reader :url, :driver` は全て削除し、インスタンス変数呼び出しに変更しました。

2021-03-04 03:13 UTC, mterada1228 commented on app/services/scraper/race_result_from_race_tab_scraper_service.rb
> +        rap_time_info: doc.css('#tab_ResultSelect_1_con > div.Result_Pay_Back.mb5 > div.ResultPayback.Block_Inline > div.Table_Scroll > table > tbody > tr:nth-child(3) > td'),
`rubocop` に `Line Length` を指摘されている箇所に関して、文字列を改行いたしました。

2021-03-04 03:14 UTC, mterada1228 commented on app/services/scraper/top_page_scraper_service.rb
> +      ActiveRecord::Base.logger = Logger.new($stdout)
ロガーは全て`Rails.logger` に吐き出すよう変更しました。

2021-03-04 03:15 UTC, mterada1228 commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +end
修正が大きくなりそうですので別MRにて対応予定です。issue に別だししましたので改めて対応します。 
 https://github.com/mterada1228/keiba_expectation_app/issues/13

2021-03-04 04:33 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +    def setup
OK

2021-03-04 04:34 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        end
OK

2021-03-04 04:35 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        return nil if elements[:horse_weight].text == '計不' || elements[:horse_weight].text.blank?
OK

2021-03-04 04:37 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +        elements[:gate_number].text.present? ? elements[:gate_number].text : nil
OK

2021-03-04 04:37 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +    attr_reader :url, :driver
OK

2021-03-04 04:38 UTC, ershn commented on app/services/scraper/race_result_from_race_tab_scraper_service.rb
> +        rap_time_info: doc.css('#tab_ResultSelect_1_con > div.Result_Pay_Back.mb5 > div.ResultPayback.Block_Inline > div.Table_Scroll > table > tbody > tr:nth-child(3) > td'),
OK

2021-03-04 04:39 UTC, ershn commented on app/services/scraper/top_page_scraper_service.rb
> +      ActiveRecord::Base.logger = Logger.new($stdout)
OK

2021-03-04 04:40 UTC, ershn commented on app/services/scraper/horse_race_from_race_page_scraper_service.rb
> +end
OK

2021-03-04 04:43 UTC, ershn approved these changes

2021-03-15 12:04 UTC, merged