馬別統計データの表示
mterada1228/keiba_expectation_app pull request #16
Opened 2021-04-07 13:11 UTC by mterada1228

2021-04-15 04:51 UTC, ershn commented on app/facades/horse_show.rb
> +end
ここの処理は馬のレース結果の統計をまとめたオブジェクトと、そのオブジェクトを生成する処理に分けるのがいいかと思いました。

クラス名・インターフェイスとしては
- `HorseEvaluation`
- `EvaluateHorse.new(horse).call`
がいいかと思います（馬を評価するところから）。

コントローラーではサービスを使うことで`HorseEvaluation`オブジェクトを生成して、ビューに直接渡して問題ないかと。

2021-04-15 04:56 UTC, ershn commented on app/facades/horse_show.rb
> +      ]
上の処理で SQL クエリが多く実行されてしまうと思いますが、それだと、パフォーマンスが問題になる可能性があります。

必要なデータすべてを取得してから、rails 側でデータの加工をした方がいいかもしれません。

2021-04-15 05:00 UTC, ershn commented on app/models/race.rb
> +  scope :unplaced_races, -> { joins(:horse_races).merge(HorseRace.unplaced_races) }
わかりやすくなるように、名前を工夫した方がいいかと思いました。

2021-04-15 05:04 UTC, mterada1228 commented on app/models/race.rb
> +  scope :unplaced_races, -> { joins(:horse_races).merge(HorseRace.unplaced_races) }
`Race` なのか `HorseRace` なのか、どのモデルを取得しようとしているのかがわかりづらい。

2021-04-19 22:26 UTC, mterada1228 commented on app/facades/horse_show.rb
> +end
馬別統計データを計算して、`HorseEvaluation` のインスタンスを作成する `EvaluateHorse` クラスを追加しました。  
`HorseController` クラスでは、`EvaluateHorse.new(@horse).call` をして、`HorseEvaluation` のインスタンスを取得します。  
View では `HorseEvaluation` のプロパティを参照して、馬別統計データの表示を実現するように修正しました。

2021-04-19 22:36 UTC, mterada1228 commented on app/facades/horse_show.rb
> +      ]
以下の処理に変更することで、SQLクエリは 16回 => 4回に削減できました。
- `EvaluateHorse#races_by_place` で初めに、その馬の1着、2着、3着、着外の `Race` を `@races_by_place` として取得する
- `EvaluateHorse#results_by_course_condition` => `create_results_by_value_hash` では、`races_by_place` の中から、`course_condition` が　`firm, good, yielding, soft` となっているレースを`Enumerable#select` で抽出して、`course_condition` 毎の 1着, 2着, 3着, 着外の回数の `Hash` を計算する

2021-04-19 22:51 UTC, mterada1228 commented on app/models/race.rb
> +  scope :unplaced_races, -> { joins(:horse_races).merge(HorseRace.unplaced_races) }
取得すべきモデルは `HorseRace` が主でなので、`hoge_place_horse_races` に修正しました。

2021-04-19 23:04 UTC, mterada1228 reviewed
`RaceResult` を `Race` に統合したことに関して、ただ単に `RaceResult` から `Race` モデルを参照するように修正した箇所と、データマイグレーションに関連するファイルは本MRと本質的には関係がないため一旦 レビューステータスを`Viewed` にしておきました。必要に応じてご確認頂ければと思います。

2021-04-22 04:39 UTC, ershn commented on app/facades/horse_show.rb
> +end
OK

2021-04-22 04:41 UTC, ershn commented on app/services/evaluate_horse.rb
> +  end
ここで SQL クエリは4つ発行されますが、全部同じテーブルで条件はほぼ一緒なので、一つの SQL クエリで全部を取得してから、Rails で処理をしたほうがパフォーマンス的にいいと思います。

2021-04-22 04:46 UTC, ershn commented on app/services/evaluate_horse.rb
> +  end
ここで事前に準備された`@races_by_place`を使ってますが、メソッドのインターフェイスでそれがわからなくて、`@races_by_place`がない状態で読んでしまうと、バグってしまうので、`@races_by_place`は引数から受け取った方が保守性的にいいです。

2021-04-22 04:47 UTC, ershn commented on app/services/evaluate_horse.rb
> +                       race.send(column) == value
Rails のカラムは `race[column]` の形でもアクセスできます。

2021-04-22 04:48 UTC, ershn commented on app/services/evaluate_horse.rb
> +                     end.count,
`count`にブロックを直接渡すことも可能です。

2021-04-22 04:51 UTC, ershn commented on app/services/evaluate_horse.rb
> +    OpenStruct.new(
OpenStruct は避けて`HorseEvaluation`と同じく名前を与えたクラスにした方がいいと思います。

2021-04-22 04:54 UTC, ershn commented on app/services/evaluate_horse.rb
> +                  end.count }
以上で select は全部いっしょなので、select を実行した上で順位でフィルターした方がいいと思います。

2021-04-22 04:55 UTC, ershn commented on app/facades/horse_show.rb
> +      ]
OK

2021-04-22 04:55 UTC, ershn commented on app/models/race.rb
> +  scope :unplaced_races, -> { joins(:horse_races).merge(HorseRace.unplaced_races) }
OK

2021-05-07 00:21 UTC, mterada1228 commented on app/services/evaluate_horse.rb
> +  end
SQL クエリの発行は1回のみ、https://github.com/mterada1228/keiba_expectation_app/blob/53a48c68850528d0a40ebdc09fea16b639ce00ad/app/services/horse_race_stats.rb#L3 で実行するように修正しました。`order_of_arrival` での絞り込み、`course_condition` での絞り込みは、ruby のメソッドで行うようにしております。

2021-05-08 05:10 UTC, mterada1228 commented on app/services/evaluate_horse.rb
> +  end
この関数自体は削除してしまいましたが、相当の処理は以下に移動しました。

https://github.com/mterada1228/keiba_expectation_app/blob/53a48c68850528d0a40ebdc09fea16b639ce00ad/app/services/horse_race_stats.rb#L10

ここではインスタンス変数を直接呼び出しせず、引数として受け取るように変更しています。

2021-05-08 05:11 UTC, mterada1228 commented on app/services/evaluate_horse.rb
> +                       race.send(column) == value
こちらの処理は `group_by` で行うように変更しましたので、該当のメソッドは削除されました。

https://github.com/mterada1228/keiba_expectation_app/blob/53a48c68850528d0a40ebdc09fea16b639ce00ad/app/services/horse_race_stats_value.rb＃L5

2021-05-08 05:13 UTC, mterada1228 commented on app/services/evaluate_horse.rb
> +                     end.count,
該当の処理は`group_by`の結果を`count`するよう変更したので、該当のメソッドは削除しました。

https://github.com/mterada1228/keiba_expectation_app/blob/53a48c68850528d0a40ebdc09fea16b639ce00ad/app/services/horse_race_stats_value.rb#L6-L8

2021-05-08 05:17 UTC, mterada1228 commented on app/services/evaluate_horse.rb
> +    OpenStruct.new(
以下の統計情報のオブジェクトをクラスとして設計しました。

1. 統計情報オブジェクト `HorseRaceStats`
2. 各統計上の値のオブジェクト `HorseRaceStatsValue`

例) `Race.course_conditions` 毎の統計情報オブジェクト
``` ruby
<HorseEvaluation:0x00007fe05d5c65f8
 @results_by_course_condition=
  #<HorseRaceStats:0x00007fe05d5c4550
   @firm=
    #<HorseRaceStatsValue:0x00007fe05c5f1768 @first_place=4, @second_place=4, @third_place=3, @unplaced=13>,
   @good=#<HorseRaceStatsValue:0x00007fe05f9afc08 @first_place=1, @second_place=1, @third_place=0, @unplaced=2>,
   @soft=#<HorseRaceStatsValue:0x00007fe060126ec8 @first_place=0, @second_place=0, @third_place=0, @unplaced=2>,
   @yielding=
    #<HorseRaceStatsValue:0x00007fe05f914cf8 @first_place=0, @second_place=0, @third_place=1, @unplaced=1>>>

2021-05-08 05:19 UTC, mterada1228 commented on app/services/evaluate_horse.rb
> +                  end.count }
順位のフィルターは、`HorseRace` の `order_of_arrival` で `group_by` することで取得するように変更しました。

https://github.com/mterada1228/keiba_expectation_app/blob/53a48c68850528d0a40ebdc09fea16b639ce00ad/app/services/horse_race_stats_value.rb#L5

2021-05-08 05:19 UTC, mterada1228 commented
@ershn 修正を行いましたので、再レビューをお願いいたします。

2021-05-13 04:46 UTC, ershn commented on app/services/horse_race_stats.rb
> +end
汎用的ですが、逆に読みにくくて保守するのも難しいと思います。

ここは属性ごとに個別なクラスを作るのは問題ないと思います。

`define_method`や`instance_variable_set`、`class_eval`などは他にやり方が本当にない時だけ使うべきです。

2021-05-13 04:47 UTC, ershn commented on app/services/horse_race_stats.rb
> +    horse_races = horse.horse_races.includes(:race)
`includes`の呼び出し順番が合ってますか？

2021-05-13 04:49 UTC, ershn commented on app/services/horse_race_stats_value.rb
> +  attr_accessor :first_place, :second_place, :third_place, :unplaced
`attr_reader`の方が適切だと思います。

2021-05-13 04:53 UTC, ershn commented on app/services/horse_race_stats_value.rb
> +class HorseRaceStatsValue
`HorsePodiums`の方が適切だと思います。

2021-05-13 04:56 UTC, ershn commented on app/services/evaluate_horse.rb
> +  end
OK

2021-05-13 04:57 UTC, ershn commented on app/services/evaluate_horse.rb
> +  end
OK

2021-05-13 04:57 UTC, ershn commented on app/services/evaluate_horse.rb
> +                       race.send(column) == value
OK

2021-05-13 04:58 UTC, ershn commented on app/services/evaluate_horse.rb
> +                     end.count,
OK

2021-05-13 05:00 UTC, ershn commented on app/services/evaluate_horse.rb
> +                  end.count }
OK

2021-05-16 07:50 UTC, mterada1228 commented on app/services/horse_race_stats.rb
> +end
個別のクラス `ResultsByCourseCondition` を作成して、メタプログラミング的な記法を避けるようにしました。  
ただ、`instance_variable_set` の箇所は良い書き方が思いつかないのですが、代わりに適した記法を相談させていただけないでしょうか...？

2021-05-16 07:53 UTC, mterada1228 commented on app/services/horse_race_stats.rb
> +    horse_races = horse.horse_races.includes(:race)
リファクタリングをして街頭のメソッドは以下に移動しました。
https://github.com/mterada1228/keiba_expectation_app/blob/b361b6da0c675a2f87cb53a0f7094d3b05e60a70/app/controllers/horses_controller.rb#L9-11

2021-05-16 07:55 UTC, mterada1228 commented on app/services/horse_race_stats_value.rb
> +  attr_accessor :first_place, :second_place, :third_place, :unplaced
こちら `attr_reader` に修正いたしました。

2021-05-16 07:55 UTC, mterada1228 commented on app/services/horse_race_stats_value.rb
> +class HorseRaceStatsValue
`HorsePodiums` に修正いたしました。

2021-05-20 04:36 UTC, ershn commented on app/services/evaluate_horse.rb
> +    OpenStruct.new(
OK

2021-05-20 04:58 UTC, ershn commented on app/services/generate_rpci_ave1f_scatter_plots_service.rb
> +      data: [[horse_race.race.RPCI, horse_race.race.ave_1F]],
ここで`race`の取得で不要な SQL が実行されないように、リレーションの設定で`inverse_of`を生かす必要があるかもしれません。

2021-05-20 04:58 UTC, ershn commented on app/services/horse_stats/evaluate_horse.rb
> +      @horse_evaluation = HorseEvaluation.new
意図しないサイド・エフェクトを避けるために、こちらの行は`call`で実行した方がいいです。

2021-05-20 04:58 UTC, ershn commented on app/services/horse_stats/results_by_course_condition.rb
> +      end
ここで汎用的に書くと、読みにくくなって、保守性が下がるので、修正時に作業が増えるかもしれませんが、ここは明示的に書いた方がいいと思います。

```ruby
by_course_condition = horse_races.group_by { |horse_race| horse_race.race.course_condition }
@firm = HorsePodiums.new(by_course_condition[:firm])
# ...
```

2021-05-20 04:58 UTC, ershn commented on app/services/horse_stats/horse_podiums.rb
> +    end
ここで５行だけなので、問題ないですが、それより多いと、全部を`initialize`の中に書くのは保守性が悪いので、以下にする方がいいです。

```ruby
def initialize(horse_races)
  @horse_races = horse_races
end

def horse_races_by_place
  @horse_races_by_place ||= horse_races.group_by(&:order_of_arrival)
end

def first_place
  @first_place ||= horse_races_by_place[1].try(:count) || 0
end

# ...
```

サイド・エフェクトのあるクラスで以上の書き方は逆に読みにくいですが、データを提供するだけの read only なモデルの場合、読みやすくなります。

2021-05-20 04:58 UTC, ershn commented on app/services/horse_race_stats.rb
> +    horse_races = horse.horse_races.includes(:race)
OK

2021-05-20 04:59 UTC, ershn commented on app/services/horse_race_stats_value.rb
> +  attr_accessor :first_place, :second_place, :third_place, :unplaced
OK

2021-05-20 04:59 UTC, ershn commented on app/services/horse_race_stats.rb
> +end
OK

2021-05-20 04:59 UTC, ershn commented on app/services/horse_race_stats_value.rb
> +class HorseRaceStatsValue
OK

2021-05-20 04:59 UTC, ershn requested changes
ご確認ください。

2021-05-23 07:07 UTC, mterada1228 commented on app/services/generate_rpci_ave1f_scatter_plots_service.rb
> +      data: [[horse_race.race.RPCI, horse_race.race.ave_1F]],
すみません、嘘つきました...  
Rails 4.1 以降では `inverse_of` を明示的に示す必要はないようです。

実際に試しましたが、複数回の SQL は実行されませんでした。

2021-05-23 07:07 UTC, mterada1228 commented on app/services/horse_stats/evaluate_horse.rb
> +      @horse_evaluation = HorseEvaluation.new
`call` メソッド内に処理を移動しました。

2021-05-23 07:10 UTC, mterada1228 commented on app/services/horse_stats/results_by_course_condition.rb
> +      end
https://github.com/mterada1228/keiba_expectation_app/blob/560e300c7b3444ab08cf86e3020068502d04d152/app/services/horse_stats/results_by_course_condition.rb#L9-L15 のように明示的に変数名を示すよう、修正しました。

2021-05-23 07:10 UTC, mterada1228 commented on app/services/horse_stats/horse_podiums.rb
> +    end
https://github.com/mterada1228/keiba_expectation_app/blob/560e300c7b3444ab08cf86e3020068502d04d152/app/services/horse_stats/horse_podiums.rb#L7-L21 のようにメソッドとして別だししました。

2021-05-27 04:33 UTC, ershn commented on app/services/horse_race_stats.rb
> +    horse_races = horse.horse_races.includes(:race)
OK

2021-05-27 04:37 UTC, ershn commented on app/controllers/horses_controller.rb
>      @horse_races = @horse.horse_races.includes(:race).order('races.start DESC')
レコードの取得は`Horse.includes(horse_races: [:race])`で行えば、下の`includes(:race)`を避けられるかもしれません。

order 区は該当のレコードはすでに取得されていれば、ruby でやっても問題なさそうです。

2021-05-27 04:39 UTC, ershn commented on app/services/generate_rpci_ave1f_scatter_plots_service.rb
> +      data: [[horse_race.race.RPCI, horse_race.race.ave_1F]],
OK

2021-05-27 04:40 UTC, ershn commented on app/services/horse_stats/evaluate_horse.rb
> +      @horse_evaluation
`@horse_evaluation`はインスタンス変数にしなくても問題ないと思います。

2021-05-27 04:40 UTC, ershn commented on app/services/horse_stats/evaluate_horse.rb
> +      @horse_evaluation = HorseEvaluation.new
OK

2021-05-27 04:41 UTC, ershn commented on app/services/horse_stats/results_by_course_condition.rb
> +    def create_stats(horse_races)
こちらは`private`にしても問題なさそうです。

2021-05-27 04:43 UTC, ershn commented on app/services/horse_stats/results_by_course_condition.rb
> +      end
OK

2021-05-27 04:48 UTC, ershn commented on app/services/horse_stats/horse_podiums.rb
> +      @by_place ||= @horse_races ? @horse_races.group_by(&:order_of_arrival) : {}
クラスがパブリックインターフェイスで受け取れるデータの形とパターンは絞った方が保守性がいいので、このクラスで`nil`を受け取れないと決めて、呼び出し箇所で必ず配列を渡すようにしたほうがいいです。

```ruby
@firm = HorsePodiums.new(by_course_condition.fetch('firm', []))
@good = HorsePodiums.new(by_course_condition.fetch('good', []))
```

2021-05-27 04:52 UTC, ershn commented on app/services/horse_stats/horse_podiums.rb
> +    def initialize(horse_races)
引数として配列しか許容しないと他メンバーに伝えたい場合はコメントでそれを説明するのが一般的です。

フォーマットとしては最近の流れからして YARD がいいと思います。

2021-05-27 04:54 UTC, ershn commented on app/services/horse_stats/horse_podiums.rb
> +    end
OK

2021-05-27 04:57 UTC, ershn commented on app/services/horse_stats/horse_evaluation.rb
> +    attr_accessor :results_by_course_condition
ここでレコードのようにいつどこでクラスのステートを変えてもいいような実装ですが、それはできる場合に避けて、使い手に選択肢が少ない実装にした方が保守性が上がります。

ここはすべてをクラスのインスタンス化時にデータを渡せばいいと思います。

2021-05-29 06:19 UTC, mterada1228 commented on app/controllers/horses_controller.rb
>      @horse_races = @horse.horse_races.includes(:race).order('races.start DESC')
頂きましたご指摘の通り修正しました。
実際に request しましたが、SQL の呼び出しは一度だけしか実行されないこと確認できました。

2021-05-29 06:20 UTC, mterada1228 commented on app/services/horse_stats/evaluate_horse.rb
> +      @horse_evaluation
https://github.com/mterada1228/keiba_expectation_app/pull/16#discussion_r640286986

上記コメントに対する修正により、 `@horse_evaluation` への代入は不必要になりましたので削除しています。

2021-05-29 06:21 UTC, mterada1228 commented on app/services/horse_stats/results_by_course_condition.rb
> +    def create_stats(horse_races)
`private` に変更しました。

2021-05-29 06:21 UTC, mterada1228 commented on app/services/horse_stats/horse_podiums.rb
> +      @by_place ||= @horse_races ? @horse_races.group_by(&:order_of_arrival) : {}
頂いたご指摘の通り修正させて頂きました。

2021-05-29 06:21 UTC, mterada1228 commented on app/services/horse_stats/horse_podiums.rb
> +    def initialize(horse_races)
YARD でコメントを追加しました。

2021-05-29 06:23 UTC, mterada1228 commented on app/services/horse_stats/horse_evaluation.rb
> +    attr_accessor :results_by_course_condition
`initialize` メソッドを追加しました。
それに伴い、呼び出し側も以下のように修正しました。

https://github.com/mterada1228/keiba_expectation_app/blob/8d0f7758e696bc6f4cd0dd8ead1b9d9db68a33f8/app/services/horse_stats/evaluate_horse.rb#L8-L13

2021-06-10 04:37 UTC, ershn commented on app/controllers/horses_controller.rb
>      @horse_races = @horse.horse_races.includes(:race).order('races.start DESC')
OK

2021-06-10 04:38 UTC, ershn commented on app/services/horse_stats/evaluate_horse.rb
> +      @horse_evaluation
OK

2021-06-10 04:38 UTC, ershn commented on app/services/horse_stats/results_by_course_condition.rb
> +    def create_stats(horse_races)
OK

2021-06-10 04:39 UTC, ershn commented on app/services/horse_stats/horse_podiums.rb
> +      @by_place ||= @horse_races ? @horse_races.group_by(&:order_of_arrival) : {}
OK

2021-06-10 04:40 UTC, ershn commented on app/services/horse_stats/horse_podiums.rb
> +    def initialize(horse_races)
OK

2021-06-10 04:43 UTC, ershn commented on app/services/horse_stats/horse_evaluation.rb
> +    attr_accessor :results_by_course_condition
OK

2021-06-10 04:45 UTC, ershn requested changes
ご確認ください。

2021-06-10 04:45 UTC, ershn commented on app/services/horse_stats/horse_evaluation.rb
> +      @results_by_course_condition = results_by_course_condition
`results`はデータの形について何も指定しない呼称なので、`podiums`と名付けた方がわかりやすいと思いました。

2021-06-10 04:45 UTC, ershn commented on app/controllers/horses_controller.rb
> +    @horse_races = @horse.horse_races.sort_by { |horse_race| horse_race.race.start }.reverse!
`!`があるメソッドだと、リシーバーの配列が変更されますが、パフォーマンスが問題じゃなければ基本的に`!`のないメソッドを使ったほうが保守性がよくなります。

----

ここは`sort_by`+`reverse`より`sort { |a, b| }`を使ったほうがパフォーマンスがいいと思います。

2021-06-14 23:11 UTC, mterada1228 commented on app/services/horse_stats/horse_evaluation.rb
> +      @results_by_course_condition = results_by_course_condition
名称を変更しました。

2021-06-14 23:12 UTC, mterada1228 commented on app/controllers/horses_controller.rb
> +    @horse_races = @horse.horse_races.sort_by { |horse_race| horse_race.race.start }.reverse!
`sort { |a, b|  b.race.start <=> a.race.start }` でレース日付の降順に並ぶようにロジックを修正しました。

2021-06-14 23:12 UTC, merged