Feature add race result scatter
mterada1228/keiba_expectation_app pull request #6
Opened 2020-10-01 01:13 UTC by mterada1228

2020-10-01 05:08 UTC, mterada1228 commented
> `races = races.all.includes(:race_result)`とすることで、SQLの発行がループのたびに行われないよう修正しました。

2020-10-01 05:09 UTC, ershn commented
> `races = races.all.includes(:race_result)`とすることで、SQLの発行がループのたびに行われないよう修正しました。

こちらは MR に含まれてないようです。

2020-10-01 05:20 UTC, ershn requested changes
レビューしましたので、ご確認ください。

2020-10-01 05:20 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +class GenerateGraphPointsService
インスタンスに対して呼び出せるメソッドは一つしかないので、クラス名とメソッド名の間で処理内容を表す情報を重複させる必要はないと思います。

```ruby
class GenerateGraphPoints
  def initialize
  end

  def call
  end
end
```

2020-10-01 05:20 UTC, ershn commented on app/controllers/horses_controller.rb
> +    @graph_points = generate_graph_point_service.generate_graph_points
メソッドの呼び出しだけなので、ここでは省略して以下のようにするのもいいかと思います。
```ruby
@graph_points = GenerateGraphPoints.new(@horse).call
```

2020-10-01 05:20 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +      graph_points(horse_race_result)
こちらのメソッドはポイントを一つだけ返すので、`s`はつけない方が適切だと思います。

2020-10-01 05:20 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +    end
以上の処理はレースの結果によって色を返すだけなので、個別のメソッドに抽出できると思います。

2020-10-01 05:20 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +    race_result = horse_race_result.race_result
ここに N + 1 問題が発生しますね。

2020-10-06 00:21 UTC, mterada1228 commented
> > `races = races.all.includes(:race_result)`とすることで、SQLの発行がループのたびに行われないよう修正しました。
> 
> こちらは MR に含まれてないようです。

https://github.com/mterada1228/keiba_expectation_app/blob/9ee916b16a7c4bfa0c046de38a1022e74cf4f20e/app/controllers/horses_controller.rb#L10

showメソッド内にて関連モデルをpreloadする処理にしました。

2020-10-06 00:23 UTC, mterada1228 commented on app/services/generate_graph_points_service.rb
> +class GenerateGraphPointsService
`call`に修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/9ee916b16a7c4bfa0c046de38a1022e74cf4f20e/app/services/generate_graph_points_service.rb#L14

2020-10-06 00:25 UTC, mterada1228 commented on app/controllers/horses_controller.rb
> +    @graph_points = generate_graph_point_service.generate_graph_points
処理をワンライナーにまとめました。

https://github.com/mterada1228/keiba_expectation_app/blob/9ee916b16a7c4bfa0c046de38a1022e74cf4f20e/app/controllers/horses_controller.rb#L11

2020-10-06 00:28 UTC, mterada1228 commented on app/services/generate_graph_points_service.rb
> +      graph_points(horse_race_result)
メソッド名は以下のように修正して、単数形かつ意味も分かりやすくなるように修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/9ee916b16a7c4bfa0c046de38a1022e74cf4f20e/app/services/generate_graph_points_service.rb#L28

https://github.com/mterada1228/keiba_expectation_app/blob/9ee916b16a7c4bfa0c046de38a1022e74cf4f20e/app/services/generate_graph_points_service.rb#L42

2020-10-06 01:09 UTC, mterada1228 commented on app/services/generate_graph_points_service.rb
> +    end
色を取得する処理は、個別のメソッドに抽出いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/ceb7d91c2319035afb6d2c3e604a89815c8738ee/app/services/generate_graph_points_service.rb#L40

2020-10-06 01:10 UTC, mterada1228 commented on app/services/generate_graph_points_service.rb
> +    race_result = horse_race_result.race_result
他箇所で問題の解決を図っております。
こちらのコメントをご参照お願い致します。

https://github.com/mterada1228/keiba_expectation_app/pull/6#issuecomment-701888111

2020-10-08 05:21 UTC, ershn commented on app/controllers/horses_controller.rb
> +                            { horse_race_results: :race_result }
- `preload`は`.preload(horse_race_results: :race_result)`で省略できると思います。
- 基本的には`includes`を使うべきで、特別な理由があるときのみ、preload か eager_load を使うべきです。
  - https://blog.bigbinary.com/2013/07/01/preload-vs-eager-load-vs-joins-vs-includes.html

2020-10-08 05:21 UTC, ershn commented on app/models/horse.rb
> +  has_many :horse_race_results
ここで直接`race_results`を取得するために、リレーションを定義することができます。

```ruby
has_many :race_results, through: :horse_race_results
```

2020-10-08 05:21 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +class GenerateGraphPointsService
OK です。

2020-10-08 05:23 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +class GenerateGraphPointsService
どのグラフが生成されるのかがわかるようにクラス名を変えたほうがいいかと思いました。

2020-10-08 05:23 UTC, ershn commented on app/controllers/horses_controller.rb
> +    @graph_points = generate_graph_point_service.generate_graph_points
OKです。

2020-10-08 05:23 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +      graph_points(horse_race_result)
OKです。

2020-10-08 05:27 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +    end
以上にある return は必要ないです。

2020-10-08 05:27 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +    end
OKです。

2020-10-08 05:27 UTC, ershn commented on app/services/generate_graph_points_service.rb
> +    race_result = horse_race_result.race_result
OKです。

2020-10-08 06:02 UTC, ershn requested changes
再レビューしましたので、ご確認ください。

2020-10-08 06:02 UTC, ershn commented on spec/factories/horse_race_results.rb
> +    association :race_result
ここは`association`を省略しても問題ないと思います。

2020-10-08 06:02 UTC, ershn commented on spec/factories/horses.rb
> +    id { Faker::Number.number(digits: 10) }
レコードのプライマリーキーを手動で生成するケースはあまりないと思います。

以下を読んでください。
- https://speakerdeck.com/toshimaru/factorybot-the-right-way

2020-10-08 06:02 UTC, ershn commented on spec/factories/race_results.rb
> +    sequence(:id) { |n| n * 12 }
以下に同じ
> レコードのプライマリーキーを手動で生成するケースはあまりないと思います。

2020-10-08 06:02 UTC, ershn commented on spec/factories/races.rb
> +    id Faker::Number.number(digits: 12)
以下に同じ
> レコードのプライマリーキーを手動で生成するケースはあまりないと思います。
----
ブロックを使わないと、アトリビュートの値は固定となるので、修正が必要です。

2020-10-08 06:02 UTC, ershn commented on spec/services/generate_graph_points_service_spec.rb
> +  let(:horse) { FactoryGirl.create(:horse) }
`FactoryGirl`から`FactoryBot`に変わったので、gem を更新した方がいいと思います。

----

必須ではないが、`FactoryGirl.`のプレフィックスを指定する必要がないように、以下のように設定できます。

https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#rspec

2020-10-08 06:02 UTC, ershn commented on spec/services/generate_graph_points_service_spec.rb
> +RSpec.describe GenerateGraphPointsService do
`RSpec`のプレフィックスを指定する必要がないかと思います。

2020-10-08 06:02 UTC, ershn commented on spec/services/generate_graph_points_service_spec.rb
> +    FactoryGirl.create(:race_result, name: 'レース', RPCI: 50, ave_1F: 14)
レコードの値の指定は、特殊な値をテストするスペックではなければ、ファクトリー内でランダムで設定するのが一般的だと思います。

2020-10-08 06:02 UTC, ershn commented on spec/services/generate_graph_points_service_spec.rb
> +                           time_diff: 1.1)
レース結果の種類を表す trait をファクトリー内で定義するとして、以上のレコード生成処理を簡略化できると思います。

2020-10-08 06:02 UTC, ershn commented on spec/services/generate_graph_points_service_spec.rb
> +    end
レコードの生成処理を DRY にするため、以下のように改善できます。
```ruby
describe do
  let(:horse_race_result) { create(:horse_race_result, trait, horse: horse, race_result: race_result) }

  context do
    let(:trait) { :win }

    it {}
  end
end
```

2020-10-08 06:02 UTC, ershn commented on spec/services/generate_graph_points_service_spec.rb
> +end
`horse_race_result`が複数あった場合のテストも追加した方が安全だと思います。

2020-10-08 06:02 UTC, ershn commented on spec/requests/races_spec.rb
> +RSpec.describe 'Races', type: :request do
もしかすると、ここだと、`type: :request`を指定する必要がないかもしれません。

2020-10-08 06:02 UTC, ershn commented on spec/requests/races_spec.rb
> +    end
レスポンスのボディもテストした方がいいと思います。

2020-10-12 09:08 UTC, mterada1228 commented on app/controllers/horses_controller.rb
> +                            { horse_race_results: :race_result }
以下のように`includes`に修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/c484d7ffdee76ffd4933bff62405abc27109fba4/app/controllers/horses_controller.rb#L10

2020-10-12 09:11 UTC, mterada1228 commented on app/models/horse.rb
> +  has_many :horse_race_results
`through`キーワードを使用したリレーションを定義いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/app/models/horse.rb#L7

2020-10-12 09:11 UTC, mterada1228 commented on app/services/generate_graph_points_service.rb
> +class GenerateGraphPointsService
クラス名を`GenerateRpciAve1fScatterPlotService`としました。
https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/app/services/generate_rpci_ave1f_scatter_plot_service.rb#L4

2020-10-12 09:12 UTC, mterada1228 commented on app/services/generate_graph_points_service.rb
> +    end
`return`を削除しました。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/app/services/generate_rpci_ave1f_scatter_plot_service.rb#L40-L49

2020-10-12 09:14 UTC, mterada1228 commented on spec/factories/horse_race_results.rb
> +    association :race_result
`association`キーワードを削除しました。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/spec/factories/horse_race_results.rb#L2-L3

2020-10-12 09:15 UTC, mterada1228 commented on spec/factories/horses.rb
> +    id { Faker::Number.number(digits: 10) }
こちらですが今回 id は自動採番ではないので、IDを指定しないと生成されませんのでそのままでも問題ないでしょうか？

2020-10-12 09:16 UTC, mterada1228 commented on spec/factories/race_results.rb
> +    sequence(:id) { |n| n * 12 }
こちらですが今回 id は自動採番ではないので、IDを指定しないと生成されません。
こちらはそのままでも問題ないでしょうか？

2020-10-12 09:17 UTC, mterada1228 commented on spec/factories/races.rb
> +    id Faker::Number.number(digits: 12)
`{}`を使う形に修正しました。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/spec/factories/races.rb#L3

2020-10-12 09:18 UTC, mterada1228 commented on spec/services/generate_graph_points_service_spec.rb
> +  let(:horse) { FactoryGirl.create(:horse) }
`factoryBot` を使用するように修正しております。
https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/Gemfile#L38

---

`rails_helper.rb`に以下を追加しています。

2020-10-12 09:19 UTC, mterada1228 commented on spec/services/generate_graph_points_service_spec.rb
> +                           time_diff: 1.1)
`horse_race_result`のfactoryで以下のように設定しました。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/spec/factories/horse_race_results.rb#L5-L22

2020-10-12 09:21 UTC, mterada1228 commented on spec/services/generate_graph_points_service_spec.rb
> +    end
ご指摘の通りDRYになるようコードを修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb#L23-L28

2020-10-12 09:21 UTC, mterada1228 commented on spec/services/generate_graph_points_service_spec.rb
> +end
以下にテストを追加しました。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb#L13-L20

2020-10-12 09:22 UTC, mterada1228 commented on spec/requests/races_spec.rb
> +RSpec.describe 'Races', type: :request do
ご指摘の通り `type: :request`は不要のようでした。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/spec/requests/races_spec.rb#L3

2020-10-12 09:23 UTC, mterada1228 commented on spec/requests/races_spec.rb
> +    end
ページのタイトルに相当する部分のテストを追加しました。

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/spec/requests/races_spec.rb#L10

https://github.com/mterada1228/keiba_expectation_app/blob/82a38651f08b48058d797ebcd847c5a840ce64a3/spec/requests/races_spec.rb#L20

2020-10-12 09:23 UTC, mterada1228 commented
指摘対応を実施しました。
改めてご確認をお願い致します。

2020-10-15 05:17 UTC, ershn commented on spec/factories/horse_race_results.rb
> +  end
`trait` は `factory` 内で定義しないと、どのファクトリーにも使えるようになります。

2020-10-15 05:17 UTC, ershn commented on app/services/generate_rpci_ave1f_scatter_plot_service.rb
> +class GenerateRpciAve1fScatterPlotService
生成されるのは複数のプロットなので、`Plot`ではなく`Plots`の方がただしいです。

2020-10-15 05:17 UTC, ershn commented on spec/factories/horse_race_results.rb
> +    association :race_result
省略できるのは`association`というキーワードだけで、リレーションの定義自体ではないです。以下をご確認ください。

https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#implicit-definition

2020-10-15 05:38 UTC, ershn requested changes
レビューしましたので、ご確認ください。

2020-10-15 05:38 UTC, ershn commented on spec/factories/horses.rb
> +    id { Faker::Number.number(digits: 10) }
はい、それなら、このままで問題ないですが、ファクトリーで id を生成するなら、同じテストでの重複を避けるため`sequence`を使った方がいいと思います。

2020-10-15 05:38 UTC, ershn commented on spec/factories/race_results.rb
> +    sequence(:id) { |n| n * 12 }
はい、それなら、問題ないです。

ただし、アプリが id の値に依存しないということなので、`* 12`は不要だと思います。

2020-10-15 05:38 UTC, ershn commented on spec/factories/races.rb
> +    id { Faker::Number.number(digits: 12) }
以下に同じ

> はい、それなら、このままで問題ないですが、ファクトリーで id を生成するなら、同じテストでの重複を避けるためsequenceを使った方がいいと思います。

2020-10-15 05:38 UTC, ershn commented on spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb
> +RSpec.describe GenerateRpciAve1fScatterPlotService do
`RSpec`のプレフィックスを指定する必要がないかと思います。

2020-10-15 05:38 UTC, ershn commented on spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb
> +    create(:race_result, name: 'レース', RPCI: 50, ave_1F: 14)
レコードの値の指定は、特殊な値をテストするスペックではなければ、ファクトリー内でランダムで設定するのが一般的だと思います。

2020-10-15 05:38 UTC, ershn commented on spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb
> +                  race_result: race_result)
レコードの生成は`before`か`let`の中で定義して、`it`の中に入れるのが一般的なやり方だと思います。

2020-10-15 05:38 UTC, ershn commented on spec/requests/races_spec.rb
> +      expect(response.body).to include 'レース一覧'
レスポンスのボディをテストする場合は、動的なデータを対象にテストした方がスペックの価値があがると思います。

2020-10-20 06:32 UTC, mterada1228 commented on spec/factories/horse_race_results.rb
> +    association :race_result
`association` は削除して、リレーションの定義のみ記載するように修正致しました。

https://github.com/mterada1228/keiba_expectation_app/blob/2a8c330d3e938188b2319ee3544a042f83ce2416/spec/factories/horse_race_results.rb#L2-L4

2020-10-20 06:33 UTC, mterada1228 commented on spec/factories/horses.rb
> +    id { Faker::Number.number(digits: 10) }
以下のように修正致しました。

https://github.com/mterada1228/keiba_expectation_app/blob/2a8c330d3e938188b2319ee3544a042f83ce2416/spec/factories/horses.rb#L3

2020-10-20 06:34 UTC, mterada1228 commented on spec/factories/race_results.rb
> +    sequence(:id) { |n| n * 12 }
以下のように修正致しました。

https://github.com/mterada1228/keiba_expectation_app/blob/2a8c330d3e938188b2319ee3544a042f83ce2416/spec/factories/race_results.rb#L3

2020-10-20 06:38 UTC, mterada1228 commented on spec/services/generate_graph_points_service_spec.rb
> +RSpec.describe GenerateGraphPointsService do
`RSpec`は削除しました。以下は一例です。
https://github.com/mterada1228/keiba_expectation_app/blob/fa06549010fc06d611e42790ce8908e7552c4be2/spec/models/horse_race_result_spec.rb#L3

2020-10-20 06:39 UTC, mterada1228 commented on spec/services/generate_graph_points_service_spec.rb
> +    FactoryGirl.create(:race_result, name: 'レース', RPCI: 50, ave_1F: 14)
ファクトリーでランダム生成されるように修正致しました。
https://github.com/mterada1228/keiba_expectation_app/blob/fa06549010fc06d611e42790ce8908e7552c4be2/spec/factories/race_results.rb#L4-L6

2020-10-20 06:40 UTC, mterada1228 commented on spec/factories/horse_race_results.rb
> +  end
`trait`は`factory`の入れ子にするように変更しました。
https://github.com/mterada1228/keiba_expectation_app/blob/fa06549010fc06d611e42790ce8908e7552c4be2/spec/factories/horse_race_results.rb#L2-L6

2020-10-20 06:40 UTC, mterada1228 commented on app/services/generate_rpci_ave1f_scatter_plot_service.rb
> +class GenerateRpciAve1fScatterPlotService
クラス名を修正致しました。
https://github.com/mterada1228/keiba_expectation_app/blob/fa06549010fc06d611e42790ce8908e7552c4be2/app/services/generate_rpci_ave1f_scatter_plots_service.rb#L4

2020-10-20 06:41 UTC, mterada1228 commented on spec/factories/races.rb
> +    id { Faker::Number.number(digits: 12) }
`sequence`でランダム値を生成するように変更しました。
https://github.com/mterada1228/keiba_expectation_app/blob/fa06549010fc06d611e42790ce8908e7552c4be2/spec/factories/races.rb#L14-L15

2020-10-20 06:43 UTC, mterada1228 commented on spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb
> +RSpec.describe GenerateRpciAve1fScatterPlotService do
`RSpec`のプレフィックスは削除しました。
https://github.com/mterada1228/keiba_expectation_app/blob/fa06549010fc06d611e42790ce8908e7552c4be2/spec/services/generate_rpci_ave1f_scatter_plots_service_spec.rb#L3

2020-10-20 06:44 UTC, mterada1228 commented on spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb
> +    create(:race_result, name: 'レース', RPCI: 50, ave_1F: 14)
こちらをご参照頂ければと思います。

https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r508243765

2020-10-20 06:45 UTC, mterada1228 commented on spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb
> +                  race_result: race_result)
`before`内で処理するように変更しました。
https://github.com/mterada1228/keiba_expectation_app/blob/fa06549010fc06d611e42790ce8908e7552c4be2/spec/services/generate_rpci_ave1f_scatter_plots_service_spec.rb#L12-L13

2020-10-20 06:46 UTC, mterada1228 commented on spec/requests/races_spec.rb
> +      expect(response.body).to include 'レース一覧'
ボディのテストは新たにフィーチャースペックを作成してそちらで実施することにしました。

2020-10-20 06:47 UTC, mterada1228 commented
本件レビューありがとうございます。
指摘対応を実施いたしました。
改めてご確認をお願い致します。

2020-10-22 05:06 UTC, ershn commented on spec/factories/horse_race_results.rb
> +    association :race_result
OK です。

2020-10-22 05:08 UTC, ershn commented on spec/factories/horses.rb
> +    id { Faker::Number.number(digits: 10) }
了解です。

`{ |n| n }`の形のブロックだと、ブロックをまるごと省けます。

https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#without-a-block

2020-10-22 05:09 UTC, ershn commented on spec/factories/race_results.rb
> +    sequence(:id) { |n| n * 12 }
以下に同じ
>了解です。
>
>`{ |n| n }`の形のブロックだと、ブロックをまるごと省けます。
>
>https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#without-a-block

2020-10-22 05:10 UTC, ershn commented on spec/services/generate_graph_points_service_spec.rb
> +RSpec.describe GenerateGraphPointsService do
OK です。

2020-10-22 05:17 UTC, ershn commented on spec/services/generate_graph_points_service_spec.rb
> +    FactoryGirl.create(:race_result, name: 'レース', RPCI: 50, ave_1F: 14)
OK です。

2020-10-22 05:19 UTC, ershn commented on spec/factories/horse_race_results.rb
> +  end
OK です。

2020-10-22 05:19 UTC, ershn commented on app/services/generate_rpci_ave1f_scatter_plot_service.rb
> +class GenerateRpciAve1fScatterPlotService
OK です。

2020-10-22 05:22 UTC, ershn commented on spec/factories/races.rb
> +    id { Faker::Number.number(digits: 12) }
以下に同じ
>了解です。
>
>`{ |n| n }`の形のブロックだと、ブロックをまるごと省けます。
>
>https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#without-a-block

2020-10-22 05:23 UTC, ershn commented on spec/services/generate_rpci_ave1f_scatter_plot_service_spec.rb
> +                  race_result: race_result)
OK です。

2020-10-22 05:26 UTC, ershn commented on spec/requests/races_spec.rb
> +      expect(response.body).to include 'レース一覧'
OK です。

2020-10-22 05:27 UTC, ershn approved these changes

2020-10-22 06:05 UTC, ershn requested changes

2020-10-22 06:05 UTC, ershn commented on app/helpers/races_helper.rb
> +    race_condition.concat(race.slice(:turn, :side, :regulation1, :regulation2, :regulation3, :regulation4).values)
`race.slice.values`の代わりに`race.values_at`は使えます。

2020-10-22 06:05 UTC, ershn commented on app/helpers/races_helper.rb
>    end
手続き型的な書き方ですが、できる場合は関数型的に書いた方がバグが発生する可能性が低くなり、保守性も上がります。

```ruby
race.values_at(:prize1, ...).map { |price| "#{prize}万" }.join(' ')
```

2020-10-22 06:05 UTC, ershn commented on app/helpers/races_helper.rb
>    end
以下に同じ
> 手続き型的な書き方ですが、できる場合は関数型的に書いた方がバグが発生する可能性が低くなり、保守性も上がります。

```ruby
race.merge(distance: "#{race[:distance]}m").values_at(:course_type, :distance, :turn, ...).reject(&:blank?).join(' ')
```

2020-10-22 06:05 UTC, ershn commented on app/helpers/races_helper.rb
> +                               :start_time, :race_cource, :round).values
ここでも`values_at`は活かせると思います。

2020-10-22 06:05 UTC, ershn commented on spec/factories/races.rb
> +end
トップレベルにメソッドを定義するのは避けた方がいいと思います。

https://vitobotta.com/2013/09/13/top-level-methods-in-ruby/

2020-10-22 06:05 UTC, ershn commented on spec/factories/races.rb
> +  time = Faker::Time.between(from: DateTime.now - 1, to: DateTime.now)
ここでは`Faker::Time.backward`を使えると思います。

2020-10-22 06:05 UTC, ershn commented on spec/factories/races.rb
> +    side { %w(内 外)[Faker::Number.within(range: 0..1)] }
データのモデリングについて。

特定の値しか許可されてないカラムでしたら、Rails の enum を使った方がいいと思います。

2020-10-22 06:05 UTC, ershn commented on spec/factories/races.rb
> +    cource_type { %w(芝 ダ 障)[Faker::Number.within(range: 0..2)] }
データのモデリングについて。

特定の値しか許可されてないカラムでしたら、Rails の enum を使った方がいいと思います。

2020-10-22 06:05 UTC, ershn commented on spec/factories/races.rb
> +    sequence(:round) { |n| "#{n}R" }
データのモデリングについて。

こちらは整数のカラムでもいいかと思います。

2020-10-22 06:05 UTC, ershn commented on spec/factories/races.rb
> +    sequence(:days) { |n| "#{n}日目" }
データのモデリングについて。

こちらは整数のカラムでもいいかと思います。

2020-10-22 06:05 UTC, ershn commented on spec/features/races_spec.rb
> +feature 'Races', type: :feature do
`features/`の配下なので、もしかすると、`type: :feature`は必要ないかもしれません。

2020-10-22 06:05 UTC, ershn commented on spec/models/horse_race_result_spec.rb
> +describe HorseRaceResult, type: :model do
モデルですが、以下に同じ

>`features/`の配下なので、もしかすると、`type: :feature`は必要ないかもしれません。

2020-10-22 06:05 UTC, ershn commented on spec/models/horse_spec.rb
> +describe Horse, type: :model do
モデルですが、以下に同じ

>`features/`の配下なので、もしかすると、`type: :feature`は必要ないかもしれません。

2020-10-22 06:05 UTC, ershn commented on spec/models/race_horse_spec.rb
> +describe RaceHorse, type: :model do
モデルですが、以下に同じ

>`features/`の配下なので、もしかすると、`type: :feature`は必要ないかもしれません。

2020-10-22 06:05 UTC, ershn commented on spec/models/race_result_spec.rb
> +describe RaceResult, type: :model do
モデルですが、以下に同じ

>`features/`の配下なので、もしかすると、`type: :feature`は必要ないかもしれません。

2020-10-22 06:05 UTC, ershn commented on spec/models/race_spec.rb
> +describe Race, type: :model do
モデルですが、以下に同じ

>`features/`の配下なので、もしかすると、`type: :feature`は必要ないかもしれません。

2020-10-22 06:05 UTC, ershn commented on spec/requests/races_spec.rb
> +end
responseの内容が正しいということも部分的でも確認した方が安全だと思います。

2020-10-22 06:05 UTC, ershn commented on spec/requests/races_spec.rb
> +    let(:race) { create(:race, race_name: 'アイビスSD') }
`race_name`は削除可能かと思います。

2020-10-28 02:56 UTC, mterada1228 commented on spec/factories/horses.rb
> +    id { Faker::Number.number(digits: 10) }
ブロックを省略いたしました。
https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/horses.rb#L3

2020-10-28 02:56 UTC, mterada1228 commented on spec/factories/race_results.rb
> +    sequence(:id) { |n| n * 12 }
ブロックを削除いたしました。
spec/factories/race_results.rb

2020-10-28 02:57 UTC, mterada1228 commented on spec/factories/races.rb
> +    id { Faker::Number.number(digits: 12) }
ブロックを削除いたしました。
https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L3

2020-10-28 02:59 UTC, mterada1228 commented on app/helpers/races_helper.rb
> +    race_condition.concat(race.slice(:turn, :side, :regulation1, :regulation2, :regulation3, :regulation4).values)
values_at を使用するよう変更いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/app/helpers/races_helper.rb#L3

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/app/helpers/races_helper.rb#L11

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/app/helpers/races_helper.rb#L26

2020-10-28 03:00 UTC, mterada1228 commented on app/helpers/races_helper.rb
>    end
関数型的に書く記法に改めました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/app/helpers/races_helper.rb#L26-L30

2020-10-28 03:01 UTC, mterada1228 commented on app/helpers/races_helper.rb
>    end
関数型的な書き方に改めました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/app/helpers/races_helper.rb#L11-L22

2020-10-28 03:01 UTC, mterada1228 commented on app/helpers/races_helper.rb
> +                               :start_time, :race_cource, :round).values
`values_at`を使用する方法に改めました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/app/helpers/races_helper.rb#L3

2020-10-28 03:03 UTC, mterada1228 commented on spec/factories/races.rb
> +end
トップレベルにはクラス名、

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L1-L2

関数は他の箇所に移動いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L35

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L42

2020-10-28 03:03 UTC, mterada1228 commented on spec/factories/races.rb
> +  time = Faker::Time.between(from: DateTime.now - 1, to: DateTime.now)
以下のように修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L43

2020-10-28 03:05 UTC, mterada1228 commented on spec/factories/races.rb
> +    side { %w(内 外)[Faker::Number.within(range: 0..1)] }
モデルに `enum` を定義いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/app/models/race.rb#L5-L7

Factoryからはランダムに`enum`から選ぶように修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L10

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L12-L13

2020-10-28 03:06 UTC, mterada1228 commented on spec/factories/races.rb
> +    cource_type { %w(芝 ダ 障)[Faker::Number.within(range: 0..2)] }
以下を参照頂けると幸いです。

https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513152256

2020-10-28 03:07 UTC, mterada1228 commented on spec/factories/races.rb
> +    sequence(:round) { |n| "#{n}R" }
整数の値を生成するように修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L5

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L8

2020-10-28 03:07 UTC, mterada1228 commented on spec/factories/races.rb
> +    sequence(:days) { |n| "#{n}日目" }
整数の値を生成するように修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/factories/races.rb#L5

2020-10-28 03:08 UTC, mterada1228 commented on spec/features/races_spec.rb
> +feature 'Races', type: :feature do
試してみましたが `type: :feature`がなくても動きましたので削除いたしました。

以下は一例です。
https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/features/races_spec.rb#L3

2020-10-28 03:09 UTC, mterada1228 commented on spec/models/horse_race_result_spec.rb
> +describe HorseRaceResult, type: :model do
試してみましたが `type: :model`がなくても動きましたので削除いたしました。

以下は一例です。
https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/models/horse_race_result_spec.rb#L3

2020-10-28 03:10 UTC, mterada1228 commented on spec/models/horse_spec.rb
> +describe Horse, type: :model do
試してみましたが `type: :model`がなくても動きましたので削除いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/models/horse_spec.rb#L3

2020-10-28 03:10 UTC, mterada1228 commented on spec/models/race_horse_spec.rb
> +describe RaceHorse, type: :model do
試してみましたが `type: :model`がなくても動きましたので削除いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/models/race_horse_spec.rb#L3

2020-10-28 03:10 UTC, mterada1228 commented on spec/models/race_result_spec.rb
> +describe RaceResult, type: :model do
試してみましたが `type: :model`がなくても動きましたので削除いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/models/race_result_spec.rb#L3

2020-10-28 03:11 UTC, mterada1228 commented on spec/models/race_spec.rb
> +describe Race, type: :model do
試してみましたが `type: :model`がなくても動きましたので削除いたしました。

https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/models/race_spec.rb#L3

2020-10-28 03:13 UTC, mterada1228 commented on spec/requests/races_spec.rb
> +end
`GET#index`
- 生成したレースが全て表示されていることを確認
https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/requests/races_spec.rb#L14-L16

'GET#show`
- 動的に生成されるレース情報が想定通り出力されていることを確認
https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/requests/races_spec.rb#L51-L54

2020-10-28 03:13 UTC, mterada1228 commented on spec/requests/races_spec.rb
> +    let(:race) { create(:race, race_name: 'アイビスSD') }
削除いたしました。
https://github.com/mterada1228/keiba_expectation_app/blob/cf701e57db1b40365d32c90dbc1b2240000f2ce0/spec/requests/races_spec.rb#L21

2020-10-28 03:14 UTC, mterada1228 commented
レビューありがとうございます。
修正いたしましたので改めてレビューお願い致しました。

2020-10-29 05:15 UTC, ershn commented on app/helpers/races_helper.rb
> +    race_condition.concat(race.slice(:turn, :side, :regulation1, :regulation2, :regulation3, :regulation4).values)
OK

2020-10-29 05:15 UTC, ershn commented on app/helpers/races_helper.rb
>    end
OK

2020-10-29 05:15 UTC, ershn commented on app/helpers/races_helper.rb
>    end
OK

2020-10-29 05:15 UTC, ershn commented on app/helpers/races_helper.rb
> +                               :start_time, :race_cource, :round).values
OK

2020-10-29 05:18 UTC, ershn commented on spec/factories/races.rb
> +end
トップレベルは最初階層という意味なので、修正は必要です。

メソッドの内容はファクトリーのアトリビュートのブロックの中に直接移動してもいいと思います。

2020-10-29 05:25 UTC, ershn commented on spec/factories/races.rb
> +  time = Faker::Time.between(from: DateTime.now - 1, to: DateTime.now)
OK

2020-10-29 05:31 UTC, ershn commented on spec/factories/races.rb
> +    side { %w(内 外)[Faker::Number.within(range: 0..1)] }
OK

2020-10-29 05:32 UTC, ershn commented on spec/factories/races.rb
> +    cource_type { %w(芝 ダ 障)[Faker::Number.within(range: 0..2)] }
OK

2020-10-29 05:34 UTC, ershn commented on spec/factories/races.rb
> +    sequence(:round) { |n| "#{n}R" }
DB のカラムの方も整数に変えた方がメリットが多いので、修正が必要です。

2020-10-29 05:36 UTC, ershn commented on spec/factories/races.rb
> +    sequence(:days) { |n| "#{n}日目" }
こちらも DB 内で整数にした方がコードの柔軟性が上がります。

2020-10-29 05:36 UTC, ershn commented on spec/features/races_spec.rb
> +feature 'Races', type: :feature do
OK

2020-10-29 05:37 UTC, ershn commented on spec/models/horse_race_result_spec.rb
> +describe HorseRaceResult, type: :model do
OK

2020-10-29 05:37 UTC, ershn commented on spec/models/horse_spec.rb
> +describe Horse, type: :model do
OK

2020-10-29 05:37 UTC, ershn commented on spec/models/race_horse_spec.rb
> +describe RaceHorse, type: :model do
OK

2020-10-29 05:37 UTC, ershn commented on spec/models/race_result_spec.rb
> +describe RaceResult, type: :model do
OK

2020-10-29 05:37 UTC, ershn commented on spec/models/race_spec.rb
> +describe Race, type: :model do
OK

2020-10-29 05:43 UTC, ershn commented on spec/requests/races_spec.rb
> +end
OK

2020-10-29 05:43 UTC, ershn commented on spec/requests/races_spec.rb
> +    let(:race) { create(:race, race_name: 'アイビスSD') }
OK

2020-10-29 05:44 UTC, ershn approved these changes

2020-10-29 05:50 UTC, ershn requested changes

2020-10-29 05:50 UTC, ershn commented on app/helpers/races_helper.rb
> +                   'regulation4').reject(&:blank?).join(' ')
避けられる場合は、Hash 内には文字列とシンボルを混ぜない方がいいと思います。

2020-10-29 05:50 UTC, ershn commented on spec/factories/races.rb
> +    start_time { formatted_race_time }
race_date と start_time は一つのカラムとして datetime として DB に保存すると、データの扱いで色々楽になると思います。

2020-10-29 05:50 UTC, ershn commented on app/models/race.rb
> +  enum side: { no_definition_of_side: 0, inner_cource: 1, external_cource: 2 }
enum で未定義という値を指定したいときは、カラムに NULL を直接格納する方が適切だと思います。

2020-10-29 05:50 UTC, ershn commented on app/models/race.rb
> +  enum cource_type: { no_definition_of_cource_type: 0, turf: 1, dirt: 2, hundle_race: 3 }
cource → course

2020-10-29 05:50 UTC, ershn commented on spec/requests/races_spec.rb
> +end
request と feature の両方をメンテナンスするにはコストがあって、両方は大体一緒なので、一つだけにまとめた方が楽だと思います。

2020-10-30 05:55 UTC, mterada1228 commented on .rubocop.yml
> +  TargetRubyVersion: 2.5.3
```suggestion
test
```

2020-11-06 01:29 UTC, mterada1228 commented on spec/factories/races.rb
>  end
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513979739

テスト

2020-11-06 01:32 UTC, mterada1228 commented on spec/factories/races.rb
> +    race_date { Faker::Time.backward }
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513979739

`formatted_race_date` と `formatted_race_time` を削除し、
`race_date` のアトリビュートのブロック内で完結するように修正いたしました。

2020-11-06 01:33 UTC, mterada1228 commented on spec/factories/races.rb
> +end
テスト

2020-11-06 01:36 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "round"
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513987712

`round` は 整数型に定義を変更しました。

2020-11-06 01:36 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "days"
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513988509

`days`は整数型に定義を変更しました。

2020-11-06 01:38 UTC, mterada1228 commented on app/helpers/races_helper.rb
> +                   'regulation4')
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513994486

全て key は string で統一致しました。

2020-11-06 01:39 UTC, mterada1228 commented on db/schema.rb
> +    t.datetime "race_date"
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513994797

`race_date`と`start_time`は合体して、`datetime`の`race_date`としました。

2020-11-06 01:42 UTC, mterada1228 commented on app/models/race.rb
> +  enum side: { inner_course: 0, external_course: 1 }
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513994969

`NULL`を許容すると、`NULL`の時にViewで表示することができず、
enum の定義文が出力されてしまう不具合を起こしてしまいます。

ですので以下のように対応したのですがいかがでしょうか？
  1. DBにはdefault値 を設定する。
      - 
  2. enum には default値を含んで定義する

2020-11-06 01:44 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "side", default: 0
https://github.com/mterada1228/keiba_expectation_app/pull/6/commits/a786f53acbdabf4fc94f9ef56b39d4ca1c18b57c#r518474440

上記コメントの目的のため、カラムのdefault値を設定いたしました。

2020-11-06 01:46 UTC, mterada1228 commented on app/helpers/races_helper.rb
> +                   'race_course',
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:47 UTC, mterada1228 commented on app/helpers/races_helper.rb
> +                   'distance',
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:47 UTC, mterada1228 commented on app/models/race.rb
> +  enum side: { inner_course: 0, external_course: 1 }
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:47 UTC, mterada1228 commented on config/locales/ja.yml
> +        external_course: 外
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:47 UTC, mterada1228 commented on db/migrate/20201105084351_rename_cource_to_course_to_race_results.rb
> +  end
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:47 UTC, mterada1228 commented on db/migrate/20201105084557_rename_cource_to_course_to_races.rb
> +  end
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:47 UTC, mterada1228 commented on db/migrate/20201105091904_add_default_to_races.rb
> +    change_column :races, :turn, :integer, default: 0
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:47 UTC, mterada1228 commented on db/schema.rb
> +    t.string "course_condition"
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:48 UTC, mterada1228 commented on db/schema.rb
> +    t.string "race_course"
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:48 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "course_type", default: 0
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:48 UTC, mterada1228 commented on spec/factories/races.rb
> +    course_type { Race.course_types.keys.sample }
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:48 UTC, mterada1228 commented on spec/features/races_spec.rb
> +      [I18n.t("enums.race.course_type.#{race[:course_type]}"),
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995105

タイポを修正いたしました。

2020-11-06 01:49 UTC, mterada1228 commented on spec/requests/races_spec.rb
> -end
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r513995471

内容が重複している request  spec は削除いたしました。

2020-11-06 01:50 UTC, mterada1228 reviewed
レビューありがとうございました。
本件修正いたしましたのでご確認をお願い致します。

2020-11-12 05:07 UTC, ershn commented on spec/factories/races.rb
> +end
OK

2020-11-12 05:08 UTC, ershn commented on spec/factories/races.rb
> +    sequence(:round) { |n| "#{n}R" }
OK

2020-11-12 05:09 UTC, ershn commented on spec/factories/races.rb
> +    sequence(:days) { |n| "#{n}日目" }
OK

2020-11-12 05:11 UTC, ershn commented on app/helpers/races_helper.rb
> +                   'regulation4').reject(&:blank?).join(' ')
OK

2020-11-12 05:14 UTC, ershn commented on spec/factories/races.rb
> +    start_time { formatted_race_time }
OK

2020-11-12 05:19 UTC, ershn commented on app/models/race.rb
> +  enum side: { no_definition_of_side: 0, inner_cource: 1, external_cource: 2 }
OK

2020-11-12 05:20 UTC, ershn commented on app/models/race.rb
> +  enum cource_type: { no_definition_of_cource_type: 0, turf: 1, dirt: 2, hundle_race: 3 }
OK

2020-11-12 05:21 UTC, ershn commented on spec/requests/races_spec.rb
> +end
OK

2020-11-12 05:22 UTC, ershn commented on spec/factories/races.rb
> +    race_date { Faker::Time.backward }
OK

2020-11-12 05:22 UTC, ershn commented on db/schema.rb
> +    t.integer "round"
OK

2020-11-12 05:22 UTC, ershn commented on db/schema.rb
> +    t.integer "days"
OK

2020-11-12 05:22 UTC, ershn commented on app/helpers/races_helper.rb
> +                   'regulation4')
OK

2020-11-12 05:22 UTC, ershn commented on db/schema.rb
> +    t.datetime "race_date"
OK

2020-11-12 05:26 UTC, ershn commented on app/models/race.rb
> +  enum side: { inner_course: 0, external_course: 1 }
データが不明との話なので、デフォルト値より、ビューで該当データを表示しない方が適切だと思います。

2020-11-12 05:26 UTC, ershn commented on db/schema.rb
> +    t.integer "side", default: 0
OK

2020-11-12 05:26 UTC, ershn commented on app/helpers/races_helper.rb
> +                   'race_course',
OK

2020-11-12 05:26 UTC, ershn commented on app/helpers/races_helper.rb
> +                   'distance',
OK

2020-11-12 05:26 UTC, ershn commented on app/models/race.rb
> +  enum side: { inner_course: 0, external_course: 1 }
OK

2020-11-12 05:26 UTC, ershn commented on config/locales/ja.yml
> +        external_course: 外
OK

2020-11-12 05:26 UTC, ershn commented on db/migrate/20201105084351_rename_cource_to_course_to_race_results.rb
> +  end
OK

2020-11-12 05:26 UTC, ershn commented on db/migrate/20201105084557_rename_cource_to_course_to_races.rb
> +  end
OK

2020-11-12 05:27 UTC, ershn commented on db/migrate/20201105091904_add_default_to_races.rb
> +    change_column :races, :turn, :integer, default: 0
OK

2020-11-12 05:27 UTC, ershn commented on db/schema.rb
> +    t.string "course_condition"
OK

2020-11-12 05:27 UTC, ershn commented on db/schema.rb
> +    t.string "race_course"
OK

2020-11-12 05:27 UTC, ershn commented on db/schema.rb
> +    t.integer "course_type", default: 0
OK

2020-11-12 05:27 UTC, ershn commented on spec/factories/races.rb
> +    course_type { Race.course_types.keys.sample }
OK

2020-11-12 05:28 UTC, ershn commented on spec/features/races_spec.rb
> +      [I18n.t("enums.race.course_type.#{race[:course_type]}"),
OK

2020-11-12 05:28 UTC, ershn commented on spec/requests/races_spec.rb
> -end
OK

2020-11-12 05:28 UTC, ershn approved these changes

2020-11-12 05:38 UTC, ershn requested changes

2020-11-12 05:38 UTC, ershn commented on db/schema.rb
>    end
- [ ] `days`という名前だと、日単位の期間を連想してしまうので、名前は`day_number`などの方が適切だと思います。
- [ ] `races`テーブルなので、`race_`でカラムをプレフィックスしない方が可読性があがると思います。
- [ ] `race_date`は日付だけではなく、日時なので、`start`か`start_datetime`の方が適切だと思います。
- [ ] 指定がない場合はカラムはデフォルトで`null: true`となりますが、`null`となりえないカラムもあると思いますので、適宜に`null: false`を追加した方が保守性があがると思います。

2020-11-12 05:38 UTC, ershn commented on app/helpers/races_helper.rb
> +        .merge('race_date' => race[:race_date].to_s(:stamp))
変わることのないモデルのアトリビュートにアクセスしたい場合は`race[:attr]`より`race.attr`の文法の方が適切だと思います。

`race[:attr]`はアトリビュートが動的に変わる可能性がある場合のみに使うべきかと思います。

2020-11-17 07:07 UTC, mterada1228 commented on app/models/race.rb
> +  enum side: { inner_course: 0, external_course: 1 }
以下のように修正を行いました。
1. `db/schema.rb#L77-80` => `dafault: 0`を削除
2. `app/helpers/races_helper.rb#L17` => `side`が`NULL`の場合はViewで非表示になるよう処理を追加
(`course_type`, `turn` は`NOT NULL`なカラムなので`NULL`の場合の処理は追加していません。）

2020-11-17 07:13 UTC, mterada1228 commented on db/schema.rb
>    end
> daysという名前だと、日単位の期間を連想してしまうので、名前はday_numberなどの方が適切だと思います。  

=> `db/schema.rb#L81` => カラム名を`day_number`に変更しております。

---
> racesテーブルなので、race_でカラムをプレフィックスしない方が可読性があがると思います。  

=> `db/schema.rb#L72, 73, 75` => カラム名に`race_`のプレフィックスがあるものは全て外しました。

---
>  race_dateは日付だけではなく、日時なので、startかstart_datetimeの方が適切だと思います。

=>  `db/schema.rb#L72` => カラム名を `start` としました。

---
> 指定がない場合はカラムはデフォルトでnull: trueとなりますが、nullとなりえないカラムもあると思いますので、適宜にnull: falseを追加した方が保守性があがると思います。

=> `db/schema.rb` => 全体的に`null: false`とできるカラムを見直して設定しました。

2020-11-17 07:15 UTC, mterada1228 commented on app/helpers/races_helper.rb
> +        .merge('race_date' => race[:race_date].to_s(:stamp))
`race.start`でアクセスするように修正致しました。
同様に`model[:attr]`でアクセスしている箇所をgrep調査して、`model.attr`の形に修正しております。

2020-11-17 07:16 UTC, mterada1228 commented
@ershn レビューありがとうございました。
修正致しましたので改めてレビューをお願い致します。

2020-11-19 05:20 UTC, ershn commented on app/models/race.rb
> +  enum side: { inner_course: 0, external_course: 1 }
OK

2020-11-19 05:26 UTC, ershn commented on app/helpers/races_helper.rb
> +        .merge('race_date' => race[:race_date].to_s(:stamp))
OK

2020-11-19 05:29 UTC, ershn commented on db/schema.rb
>    end
OK

2020-11-19 05:30 UTC, ershn approved these changes

2020-11-19 05:34 UTC, ershn requested changes

2020-11-19 05:34 UTC, ershn commented on app/helpers/races_helper.rb
> +               'side' => side)
`side`に関する処理は個別の分岐をなくすために以下のように改善できます。

```ruby
side.try { |side| I18n.t("enums.race.side.#{side}") }
```

2020-11-19 05:34 UTC, ershn commented on app/helpers/races_helper.rb
> +    side = I18n.t("enums.race.side.#{race.side}") if race.side.present?
この場合は`side`は`nil`だということになるので、`.present?`の使用は必要ないと思います。

2020-11-19 05:34 UTC, ershn commented on app/helpers/races_helper.rb
> +    day_number = "#{race.day_number}日目" if race.day_number.present?
以下に同じ
> この場合はsideはnilだということになるので、.present?の使用は必要ないと思います。

2020-11-19 05:34 UTC, ershn commented on app/helpers/races_helper.rb
> +               'day_number' => day_number,
以下に同じ
> `side`に関する処理は個別の分岐をなくすために以下のように改善できます。
> 
> ```ruby
> side.try { |side| I18n.t("enums.race.side.#{side}") }
> ```

2020-11-19 05:54 UTC, ershn requested changes

2020-11-19 05:54 UTC, ershn commented on app/models/horse.rb
> +  has_many :race_horses
ここに`Race`の以下のリレーションの反対を定義しておいてもいいと思います。
```
has_many :horses, through: :race_horses
```

2020-11-19 05:54 UTC, ershn commented on config/initializers/time_formats.rb
> +Time::DATE_FORMATS[:stamp] = "%Y/%m/%d %H:%M" # YYYYMMDDHHMMSS
`strftime`を直接使うのが一般かなと思いますが、この使い方のままにするなら、`stamp`より内容をわかりやすく伝える名前にしたほうがいいと思います。

`:date_hour_min`とかがいいかと思います。

2020-11-19 05:54 UTC, ershn commented on db/schema.rb
>    end
完走しなかった馬さんのためのスペシャル値を各カラムで許容する必要がないように、完走しなかった理由を個別のカラムで管理してもいいかと思います。

2020-11-19 05:54 UTC, ershn commented on db/schema.rb
>      t.string "horse_id"
該当テーブルの`id`は`integer`のようです。

2020-11-19 05:56 UTC, merged