Feature add rspec
mterada1228/keiba_expectation_app pull request #7
Opened 2020-10-01 01:26 UTC by mterada1228

2020-10-01 05:42 UTC, ershn requested changes
全部ではないですが、レビューをしましたので、ご確認ください。

2020-10-01 05:42 UTC, ershn commented on Gemfile
> +  gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
github の master ブランチのものをそのまま使う理由がなければ、普通は rubygem のものを使うべきです。

faker だと、以下の方が正しいとおもいます。

```ruby
gem 'faker', '~> 2.14'
```

https://rubygems.org/gems/faker/versions/2.14.0

2020-10-01 05:42 UTC, ershn commented on Gemfile
> +gem "chartkick"
Gemfile では基本的に`~>`でバージョンを全部指定するか、何も指定しないかが一般的だと思います。

両方のやり方にメリットとデメリットがあるので、ご確認ください。

2020-10-01 05:42 UTC, ershn commented on app/controllers/races_controller.rb
> +    @race = Race.find_by_id(params[:id])
`find`はプライマリーキーで探すので、ここで`find_by_id`を使う必要がないと思います。

2020-10-01 05:42 UTC, ershn commented on app/helpers/races_helper.rb
>    def race_description_row3(race)
row1, 2, 3 はその名前だと、何を指してるのかがわからないので、表現しているデータを表す名前にした方がいいと思います。

2020-10-01 05:42 UTC, ershn commented on db/schema.rb
> +    t.integer "id", null: false
このテーブルにはプライマリーキーがないですが、検索が遅くなるのと、各レコードを特定するためのユニークな値がないということになるので、極力避けるべきだと思います。

2020-10-01 05:42 UTC, ershn commented on app/models/horse.rb
> +  self.primary_key = :id
プライマリーキーは id としてテーブル定義で指定していれば、ここで再度定義する必要がないかと思います。

2020-10-01 05:42 UTC, ershn commented on app/models/race.rb
> +  self.primary_key = :id
> プライマリーキーは id としてテーブル定義で指定していれば、ここで再度定義する必要がないかと思います。

2020-10-05 00:00 UTC, mterada1228 commented on Gemfile
> +  gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
GemFIleを修正して、ご指摘いただいた形に修正いたしました。

2020-10-05 01:40 UTC, mterada1228 commented on Gemfile
> +gem "chartkick"
全てバージョンの指定ありに修正いたしました。

2020-10-05 01:44 UTC, mterada1228 commented on app/controllers/races_controller.rb
> +    @race = Race.find_by_id(params[:id])
`find`に修正いたしました。

2020-10-05 01:52 UTC, mterada1228 commented on app/helpers/races_helper.rb
>    def race_description_row3(race)
それぞれ以下のように修正致しました。
+ `row1` => `race_schedule`
+ `row2` => `race_condition`
+ `row3` => `race_prizes`

2020-10-05 03:16 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "id", null: false
`primary_key`を明示的に指定いたしました。
また`schema.rb`上での表示のされ方は2パターンになっております。
1. 複合キーの場合
     +  (例) horse_race_results : `primary_key: ["horse_id", "race_result_id"]`
2. 単一キーの場合
     + (例) horses : `id: :bigint`

2020-10-05 04:24 UTC, mterada1228 commented on app/models/horse.rb
> +  self.primary_key = :id
定義を削除いたしました。

2020-10-05 04:24 UTC, mterada1228 commented on app/models/race.rb
> +  self.primary_key = :id
定義を削除しました

2020-10-05 04:25 UTC, mterada1228 commented
ここまで頂いた指摘について対応いたしましたので、改めてご確認をお願い致します。

2020-12-02 01:34 UTC, mterada1228 commented
`feature-add-raceResult-scatter` ブランチをマージ致しました。
改めてご確認をお願い致します。

2020-12-03 05:06 UTC, ershn commented on Gemfile
> +  gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
OK

2020-12-03 05:09 UTC, ershn commented on Gemfile
> +gem "chartkick"
OK

2020-12-03 05:11 UTC, ershn commented on app/controllers/races_controller.rb
> +    @race = Race.find_by_id(params[:id])
OK

2020-12-03 05:12 UTC, ershn commented on app/helpers/races_helper.rb
>    def race_description_row3(race)
OK

2020-12-03 05:15 UTC, ershn commented on db/schema.rb
> +    t.integer "id", null: false
OK

2020-12-03 05:16 UTC, ershn commented on app/models/horse.rb
> +  self.primary_key = :id
OK

2020-12-03 05:16 UTC, ershn commented on app/models/race.rb
> +  self.primary_key = :id
OK

2020-12-03 05:16 UTC, ershn approved these changes

2020-12-03 05:41 UTC, ershn requested changes
差分にコメントを残しましたので、ご確認ください。

追加で以下も対応をお願いします。

`db/seeds.rb`に DB に入れるデータがすべて入ってるとのことですが、そのファイルがでかいので、リポジトリのデータ領域を無駄に使ってしまうのと、バージョン管理をする必要がないものなので、データはそれぞれの環境でスクリプトを通してライブで DBに入れるべきだと思います。

2020-12-03 05:41 UTC, ershn commented on Gemfile
>  gem 'bootsnap', '>= 1.4.2', require: false
`>=`のみだと、それ以上のバージョンで何でもオッケーという意味になるので、アップデートでメージャーバージョンが変わってしまって、コードがそのままバグってしまうようになるかもしれません。

https://semver.org/

それを避けるために、さらに`~>`で許容されてるバージョンを指定する必要があります。

2020-12-03 05:41 UTC, ershn commented on db/schema.rb
> +  create_table "horses", id: :bigint, default: nil, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
こちらの`default: nil`が必要かどうかは確認をお願いします。

2020-12-03 05:41 UTC, ershn commented on app/controllers/races_controller.rb
> +    @race_horses = @race.race_horses_sorted_by_horse_number
以下のようにでも書けると思います。
```
@race.race_horses.order('horse_number')
```

2020-12-03 05:41 UTC, ershn commented on config/database.yml
>    url: postgres://ieyrutiplidged:efb177262cbd2360942202d0b9d2c91dbff9c2a346dd6ae464f4753cf5d857eb@ec2-54-158-222-248.compute-1.amazonaws.com:5432/d9c9qim5bhf600
testとdevelopmentではあまり問題にならないが、誰でも閲覧できちゃうので、このファイルでパスワードは管理しないべきです。

ローカルにパスワードを管理するや、別な、パスワードが公開されない形で管理したほうが安全です。

2020-12-03 05:41 UTC, ershn commented on config/webpacker.yml
> +  check_yarn_integrity: false
開発でこちらのほうが便利という話でしたが、セキュリティー的には危険な設定かと思いますので、無効化せずに開発時の他の対策を考えたほうが安全だと思います。

2020-12-08 02:43 UTC, mterada1228 commented on Gemfile
>  gem 'bootsnap', '>= 1.4.2', require: false
`Gemfile`を修正し全て`~>`に変更しました。

2020-12-08 02:45 UTC, mterada1228 commented on db/schema.rb
> +  create_table "horses", id: :bigint, default: nil, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
DBのテーブル定義上、`null`が不可になっています。
明示的に `default:nil`が表示されてしまっていますが、
実際には`null`が入ることはないので問題ないと判断しております。

![image](https://user-images.githubusercontent.com/49284339/101431646-a693cf80-394a-11eb-84cf-f1950fdf73e9.png)

2020-12-08 02:47 UTC, mterada1228 commented on app/controllers/races_controller.rb
> +    @race_horses = @race.race_horses_sorted_by_horse_number
以下の対応を実施しました。
1. `app/controllers/races_controller.rb` にご指摘いただいた内容の処理を追加
2. `app/models/race.rb` から`race_horses_sorted_by_horse_number`のメソッドを削除

2020-12-08 02:49 UTC, mterada1228 commented on config/database.yml
>    url: postgres://ieyrutiplidged:efb177262cbd2360942202d0b9d2c91dbff9c2a346dd6ae464f4753cf5d857eb@ec2-54-158-222-248.compute-1.amazonaws.com:5432/d9c9qim5bhf600
`config/credentials.yml.enc` にパスワードを記載し、
`database.yml`からは`credentials.yml`の内容を参照するように変更しました。

`config/credentials.yml.enc`  の内容を確認する場合は、別途 `master.key` を slackにて送付いたします。

2020-12-08 02:49 UTC, mterada1228 commented on config/webpacker.yml
> +  check_yarn_integrity: false
`false` => `true` に変更いたしました。

2020-12-08 02:51 UTC, mterada1228 commented
レビューありがとうございました。
指摘対応を行いましたのでレビューをお願い致します。

2020-12-10 05:08 UTC, ershn commented on Gemfile
>  gem 'bootsnap', '>= 1.4.2', require: false
OK

2020-12-10 05:10 UTC, ershn commented on db/schema.rb
> +  create_table "horses", id: :bigint, default: nil, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
OK

2020-12-10 05:11 UTC, ershn commented on app/controllers/races_controller.rb
> +    @race_horses = @race.race_horses_sorted_by_horse_number
OK

2020-12-10 05:12 UTC, ershn commented on config/database.yml
>    url: postgres://ieyrutiplidged:efb177262cbd2360942202d0b9d2c91dbff9c2a346dd6ae464f4753cf5d857eb@ec2-54-158-222-248.compute-1.amazonaws.com:5432/d9c9qim5bhf600
OK

2020-12-10 05:13 UTC, ershn commented on config/webpacker.yml
> +  check_yarn_integrity: false
OK

2020-12-10 05:25 UTC, ershn approved these changes

2020-12-10 05:30 UTC, ershn requested changes

2020-12-10 05:30 UTC, ershn commented on Gemfile
> +gem 'sass-rails', '~> 6'
バージョンナンバーは一つしか時は`~>`は`>=`と同じ意味を持つので、ナンバーは２つ以上が必要です。

2020-12-10 05:30 UTC, ershn commented on spec/models/race_spec.rb
>  require 'rails_helper'
こちらの`require`は裏で自動的に行われて、明示的に書く必要はないかもしれません。

2020-12-10 05:30 UTC, ershn commented on spec/models/race_spec.rb
> +describe Race, type: :model do
`type: :model`と`type: :request`の指定は必要ないと思います。

2020-12-10 05:30 UTC, ershn commented on spec/requests/races_spec.rb
> +    end
以上の２つのテストで実行されてる処理（`get race_path(race)`）は一緒なので、一つのテストに`expect`を統合するのがいいかと思います。

そうすれば、無駄な処理を避けて、テスト全体の実行が早く終わるようになります。

2020-12-10 05:30 UTC, ershn commented on spec/requests/races_spec.rb
> +      expect(response).to be_successful
レスポンスが成功しただけではなく、html に出力されたデータも期待通りのものとなってるのもテストしたほうが安全だと思います。

2020-12-15 09:41 UTC, mterada1228 commented on spec/requests/races_spec.rb
> +    end
`リクエストに正常に応答できること` と `レースに出走する競走馬が馬番の昇順でソートされていること` の `it` は一つにまとめました。

2020-12-15 09:41 UTC, mterada1228 commented on Gemfile
> +gem 'sass-rails', '~> 6'
1桁しかバージョンの指定のないgemは、2桁以上で指定するように変更しております。

2020-12-15 09:42 UTC, mterada1228 commented on spec/models/race_spec.rb
>  require 'rails_helper'
以下の2つの手順で修正を実施いたしました。
1. `.rspec` に以下を記載
```
--require rails_helper
```
2. `./spec/*`より `require` 文を削除

2020-12-15 09:42 UTC, mterada1228 commented on spec/models/race_spec.rb
> +describe Race, type: :model do
`./spec/* ` のファイルより、 `type: `の指定は削除しました。

2020-12-15 09:44 UTC, mterada1228 commented on spec/requests/races_spec.rb
> +      expect(response).to be_successful
フィーチャースペックに HTML のテストを追加しております。
- `spec/features/races_spec.rb`
- `spec/features/horses_spec.rb`

2020-12-15 09:44 UTC, mterada1228 commented
@ershn レビューありがとうございます。
修正を実施致しましたので、改めてご確認をお願い致します。

2020-12-17 06:04 UTC, ershn commented on Gemfile
> +gem 'sass-rails', '~> 6'
OK

2020-12-17 06:05 UTC, ershn commented on spec/models/race_spec.rb
>  require 'rails_helper'
OK

2020-12-17 06:06 UTC, ershn commented on spec/models/race_spec.rb
> +describe Race, type: :model do
OK

2020-12-17 06:10 UTC, ershn commented on spec/requests/races_spec.rb
> +    end
OK

2020-12-17 06:17 UTC, ershn commented on spec/requests/races_spec.rb
> +      expect(response).to be_successful
OK

2020-12-17 06:18 UTC, ershn approved these changes

2020-12-17 06:19 UTC, ershn commented
`spec/requests/`配下のものは`spec/features/`のものと重複してるので、削除をお願いします。

2020-12-17 06:26 UTC, ershn commented
`horses_controller.rb`内で`Horse.includes(:race_results).find(params[:id])`の`includes`は不要だと思います。

2020-12-17 06:29 UTC, ershn commented
`try`は`param.try { |param| }`のようにも使えますので、コードを省略できます。

2020-12-17 07:12 UTC, merged