指摘対応
mterada1228/keiba_expectation_app pull request #9
Opened 2020-11-19 06:01 UTC by mterada1228

2020-11-25 09:25 UTC, mterada1228 reviewed
@ershn 本件指摘対応を行いました。レビューをお願い致します。

2020-11-25 09:25 UTC, mterada1228 commented on app/helpers/races_helper.rb
> +               'side' => race.side.try { I18n.t("enums.race.side.#{race.side}") })
以下のコメントの指摘に対応致しました。

https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r526604167
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r526604294

2020-11-25 09:25 UTC, mterada1228 commented on app/helpers/races_helper.rb
> +               'day_number' => race.day_number.try { "#{race.day_number}日目" },
以下のコメントの指摘に対応致しました。

https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r526604412
https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r526604638

2020-11-25 09:25 UTC, mterada1228 commented on app/models/horse.rb
> +  has_many :races, through: :race_horses
以下の指摘に対応致しました。

https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r526606465

2020-11-25 09:25 UTC, mterada1228 commented on config/initializers/time_formats.rb
> +Time::DATE_FORMATS[:date_hour_min] = "%Y/%m/%d %H:%M" # YYYYMMDDHHMMSS
以下の指摘に対応致しました。

https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r526608478

2020-11-25 09:25 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "reason_of_exclusion", default: 0
以下の指摘に対応する形に対応する形で修正を行いました。
1. `reason_of_exclusion`カラムを追加。完走できずに除外された理由をEnumで格納
2. スペシャル値を想定して `String` にしていた `order_of_arrival`, `time` をそれぞれ適切なData型に修正

https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r526609836

2020-11-25 09:25 UTC, mterada1228 commented on db/schema.rb
> +    t.bigint "horse_id", null: false
以下のコメントに対応致しました。

https://github.com/mterada1228/keiba_expectation_app/pull/6#discussion_r526610284

2020-11-26 05:12 UTC, ershn commented on app/helpers/races_helper.rb
> +               'side' => race.side.try { I18n.t("enums.race.side.#{race.side}") })
OK

2020-11-26 05:13 UTC, ershn commented on app/helpers/races_helper.rb
> +               'day_number' => race.day_number.try { "#{race.day_number}日目" },
OK

2020-11-26 05:15 UTC, ershn commented on app/models/horse.rb
> +  has_many :races, through: :race_horses
OK

2020-11-26 05:17 UTC, ershn commented on config/initializers/time_formats.rb
> +Time::DATE_FORMATS[:date_hour_min] = "%Y/%m/%d %H:%M" # YYYYMMDDHHMMSS
OK

2020-11-26 05:21 UTC, ershn commented on db/schema.rb
> +    t.integer "reason_of_exclusion", default: 0
OK

2020-11-26 05:23 UTC, ershn commented on db/schema.rb
> +    t.bigint "horse_id", null: false
OK

2020-11-26 05:23 UTC, ershn approved these changes

2020-11-26 05:32 UTC, ershn requested changes

2020-11-26 05:32 UTC, ershn commented on db/schema.rb
> +    t.integer "reason_of_exclusion", default: 0
こちらは未指定の場合、`null`とする方が適切だと思いますので、`default: 0`が必要ないかと思います。

2020-12-01 23:48 UTC, mterada1228 commented on db/schema.rb
> +    t.integer "reason_of_exclusion", default: 0
以下のように修正いたしました。

https://github.com/mterada1228/keiba_expectation_app/pull/9/commits/4ee6d7eb54b136b6e3aa4c7e769ccd1f0aec3e4a#L34

2020-12-01 23:50 UTC, mterada1228 commented
レビューありがとうございます。
修正いたしましたのでご確認をお願い致します。

2020-12-03 05:03 UTC, ershn commented on db/schema.rb
> +    t.integer "reason_of_exclusion", default: 0
OK

2020-12-03 05:04 UTC, ershn approved these changes

2020-12-03 06:09 UTC, merged